In [1]:
# Unzip the uploaded file into the specified directory
!unzip -o /content/chanel-json.zip

Archive:  /content/chanel-json.zip
   creating: chanel-json/
  inflating: chanel-json/fragrance1.json
  inflating: chanel-json/fragrance2.json
  inflating: chanel-json/fragrance3.json
  inflating: chanel-json/fragrance4.json
  inflating: chanel-json/fragrance5.json
  inflating: chanel-json/fragrance6.json
  inflating: chanel-json/fragrance7.json
  inflating: chanel-json/fragrance8.json
  inflating: chanel-json/fragrance9.json
  inflating: chanel-json/makeup1.json
  inflating: chanel-json/makeup2.json
  inflating: chanel-json/makeup3.json
  inflating: chanel-json/makeup4.json
  inflating: chanel-json/makeup5.json
  inflating: chanel-json/makeup6.json
  inflating: chanel-json/makeup7.json
  inflating: chanel-json/skincare1.json
  inflating: chanel-json/skincare2.json
  inflating: chanel-json/skincare3.json
  inflating: chanel-json/skincare4.json
  inflating: chanel-json/skincare5.json

In [2]:
import json
import os
from glob import glob
from bs4 import BeautifulSoup


def extract_products_from_html(html_string, base_url="https://www.chanel.com"):
    soup = BeautifulSoup(html_string, "html.parser")
    results = []

    products = soup.find_all("article", class_="product")

    for p in products:
        try:
            product = {}

            # --- Product ID / SKU ---
            product_id = p.get("data-id")
            product["product_id"] = product_id
            product["sku"] = product_id  # same in this structure

            # --- Name ---
            name_tag = p.find("span", class_="txt-product__title")
            product["product_name"] = name_tag.get_text(strip=True) if name_tag else None

            # --- Price ---
            price_tag = p.find("p", class_="is-price")
            if price_tag:
                price_text = price_tag.get_text(strip=True)
                product["price"] = price_text.replace("AED", "").strip()
            else:
                product["price"] = None

            # --- Product URL ---
            link_tag = p.find("a", href=True)
            if link_tag:
                product["product_url"] = base_url + link_tag["href"]
            else:
                product["product_url"] = None

            # --- Image URL ---
            img_tag = p.find("img")
            if img_tag:
                product["image_url"] = img_tag.get("data-src")
            else:
                product["image_url"] = None

            # --- Category & Subcategory ---
            parent_div = p.find_parent("div", class_="product-grid__item")
            if parent_div:
                product["category"] = parent_div.get("data-product-category")
                product["sub_category"] = parent_div.get("data-product-subcategory")
            else:
                product["category"] = None
                product["sub_category"] = None

            # --- Brand ---
            # Not explicitly available → infer from image/title
            if img_tag and img_tag.get("alt"):
                product["brand"] = img_tag["alt"].split()[0]
            else:
                product["brand"] = None

            # --- Variant ---
            desc_tag = p.find("span", class_="js-ellipsis")
            product["variant"] = desc_tag.get_text(strip=True) if desc_tag else None

            # --- Availability / Quantity ---
            # Not available → assume in stock if button exists
            add_btn = p.find("button", class_="quickview-add-to-bag")
            product["quantity"] = 1 if add_btn else 0

            results.append(product)

        except Exception as e:
            print(f"Error parsing product: {e}")

    return results


def process_json_files(folder_path):
    all_products = []
    seen_ids = set()

    files = glob(os.path.join(folder_path, "*.json"))

    for file in files:
        print(f"Processing: {file}")

        with open(file, "r", encoding="utf-8") as f:
            data = json.load(f)

        html_string = data.get("productListPage")

        if not html_string:
            continue

        products = extract_products_from_html(html_string)

        for p in products:
            if p["product_id"] not in seen_ids:
                seen_ids.add(p["product_id"])
                all_products.append(p)

    return all_products


def save_to_json(data, output_file):
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


if __name__ == "__main__":
    folder_path = "chanel-json"  # change this
    output_file = "products_clean.json"

    products = process_json_files(folder_path)
    save_to_json(products, output_file)

    print(f"\n✅ Extracted {len(products)} products")

Processing: chanel-json/fragrance7.json
Processing: chanel-json/makeup2.json
Processing: chanel-json/skincare3.json
Processing: chanel-json/skincare5.json
Processing: chanel-json/makeup4.json
Processing: chanel-json/skincare4.json
Processing: chanel-json/fragrance3.json
Processing: chanel-json/fragrance5.json
Processing: chanel-json/fragrance8.json
Processing: chanel-json/makeup1.json
Processing: chanel-json/fragrance1.json
Processing: chanel-json/makeup5.json
Processing: chanel-json/fragrance2.json
Processing: chanel-json/skincare2.json
Processing: chanel-json/makeup3.json
Processing: chanel-json/fragrance6.json
Processing: chanel-json/fragrance9.json
Processing: chanel-json/fragrance4.json
Processing: chanel-json/skincare1.json
Processing: chanel-json/makeup7.json
Processing: chanel-json/makeup6.json

✅ Extracted 459 products

In [3]:
import pandas as pd

df = pd.DataFrame(products)
display(df.head())

,product_id,sku,product_name,price,product_url,image_url,category,sub_category,brand,variant,quantity
0,121880,121880,ALLURE HOMME,205,https://www.chanel.com/ae-en/fragrance/p/12188...,"https://www.chanel.com/images/t_one//w_0.51,h_...",Bath and Body,Men,CHANEL,SOAP,1
1,121820,121820,ALLURE HOMME,425,https://www.chanel.com/ae-en/fragrance/p/12182...,"https://www.chanel.com/images/t_one//w_0.51,h_...",Bath and Body,Men,CHANEL,ALL-OVER SPRAY,1
2,121700,121700,ALLURE HOMME,210,https://www.chanel.com/ae-en/fragrance/p/12170...,"https://www.chanel.com/images/t_one//w_0.51,h_...",Bath and Body,Men,CHANEL,DEODORANT STICK,1
3,121270,121270,ALLURE HOMME,350,https://www.chanel.com/ae-en/fragrance/p/12127...,"https://www.chanel.com/images/t_one//w_0.51,h_...",Bath and Body,Men,CHANEL,AFTER SHAVE LOTION,1
4,121250,121250,ALLURE HOMME,300,https://www.chanel.com/ae-en/fragrance/p/12125...,"https://www.chanel.com/images/t_one//w_0.55,h_...",Bath and Body,Men,CHANEL,AFTER SHAVE MOISTURISER,1

In [ ]:
# Save the DataFrame to a CSV file
df.to_csv("products_clean.csv", index=False)

print("DataFrame successfully saved to products_clean.csv")

DataFrame successfully saved to products_clean.csv

In [4]:
import json
import os
from glob import glob

def extract_products_from_file(file_path):
    results = []

    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    product_list = data.get("dataLayer", {}).get("productList", {})

    for product_key, product_value in product_list.items():
        try:
            products = (
                product_value
                .get("quickviewPopin", {})
                .get("ecommerce", {})
                .get("detail", {})
                .get("products", [])
            )

            for p in products:
                product = {}

                # Basic fields
                product["product_name"] = p.get("name")
                product["price"] = p.get("price")
                product["product_id"] = p.get("id")
                product["sku"] = p.get("sku_id")
                product["variant"] = p.get("variant")
                product["brand"] = p.get("brand")
                product["quantity"] = p.get("quantity")

                # Category parsing
                raw_category = p.get("category", "")
                category_parts = raw_category.split("/")

                product["category"] = category_parts[1] if len(category_parts) > 1 else None
                product["sub_category"] = category_parts[2] if len(category_parts) > 2 else None

                # Product URL
                page_url = (
                    product_value
                    .get("quickviewPopin", {})
                    .get("page")
                )
                product["product_url"] = page_url

                # Image URL (not in your sample → set None safely)
                product["image_url"] = None

                results.append(product)

        except Exception as e:
            print(f"Error processing product {product_key} in {file_path}: {e}")

    return results


def process_folder(folder_path):
    all_products = []
    seen_ids = set()

    files = glob(os.path.join(folder_path, "*.json"))

    for file in files:
        print(f"Processing: {file}")
        products = extract_products_from_file(file)

        for p in products:
            # Deduplicate using product_id
            if p["product_id"] not in seen_ids:
                seen_ids.add(p["product_id"])
                all_products.append(p)

    return all_products


def save_to_json(data, output_file):
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


if __name__ == "__main__":
    folder_path = "chanel-json"   # <-- change this
    output_file = "clean_products2.json"

    products = process_folder(folder_path)
    save_to_json(products, output_file)

    print(f"\n✅ Extracted {len(products)} unique products")

Processing: chanel-json/fragrance7.json
Processing: chanel-json/makeup2.json
Processing: chanel-json/skincare3.json
Processing: chanel-json/skincare5.json
Processing: chanel-json/makeup4.json
Processing: chanel-json/skincare4.json
Processing: chanel-json/fragrance3.json
Processing: chanel-json/fragrance5.json
Processing: chanel-json/fragrance8.json
Processing: chanel-json/makeup1.json
Processing: chanel-json/fragrance1.json
Processing: chanel-json/makeup5.json
Processing: chanel-json/fragrance2.json
Processing: chanel-json/skincare2.json
Processing: chanel-json/makeup3.json
Processing: chanel-json/fragrance6.json
Processing: chanel-json/fragrance9.json
Processing: chanel-json/fragrance4.json
Processing: chanel-json/skincare1.json
Processing: chanel-json/makeup7.json
Processing: chanel-json/makeup6.json

✅ Extracted 459 unique products

In [5]:
import pandas as pd

# Load the clean_products2.json file into a DataFrame
df_clean = pd.read_json("clean_products2.json")

# Display the first 5 rows of the DataFrame
display(df_clean.head())

,product_name,price,product_id,sku,variant,brand,quantity,category,sub_category,product_url,image_url
0,coco body cream,440,p113940,113990,(not set)/150 g,fnb,1,fragrance,women,/ae-en/fragrance/p/113990/coco-body-cream/quic...,NaN
1,egoiste deodorant stick,210,p114700,114700,(not set)/60 g,fnb,1,fragrance,bath and body,/ae-en/fragrance/p/114700/egoiste-deodorant-st...,NaN
2,coco mademoiselle fragrance primer,540,p116690,116690,(not set)/100 ml,fnb,1,fragrance,women,/ae-en/fragrance/p/116690/coco-mademoiselle-fr...,NaN
3,coco mademoiselle body oil,565,p116700,116700,(not set)/200 ml,fnb,1,fragrance,women,/ae-en/fragrance/p/116700/coco-mademoiselle-bo...,NaN
4,coco mademoiselle silky body cream,440,p116790,116790,(not set)/150 g,fnb,1,fragrance,women,/ae-en/fragrance/p/116790/coco-mademoiselle-si...,NaN

In [6]:
# Clean the 'price' column to extract numeric values for AED
df_clean['price_aed'] = df_clean['price'].astype(str).str.replace('AED', '', regex=False).str.replace(',', '', regex=False)
df_clean['price_aed'] = pd.to_numeric(df_clean['price_aed'], errors='coerce')

# Convert AED to USD (1 AED = 0.27 USD)
df_clean['price_usd'] = df_clean['price_aed'] * 0.27

# Display the DataFrame with the new price columns
display(df_clean.head())

,product_name,price,product_id,sku,variant,brand,quantity,category,sub_category,product_url,image_url,price_aed,price_usd
0,coco body cream,440,p113940,113990,(not set)/150 g,fnb,1,fragrance,women,/ae-en/fragrance/p/113990/coco-body-cream/quic...,NaN,440,118.80
1,egoiste deodorant stick,210,p114700,114700,(not set)/60 g,fnb,1,fragrance,bath and body,/ae-en/fragrance/p/114700/egoiste-deodorant-st...,NaN,210,56.70
2,coco mademoiselle fragrance primer,540,p116690,116690,(not set)/100 ml,fnb,1,fragrance,women,/ae-en/fragrance/p/116690/coco-mademoiselle-fr...,NaN,540,145.80
3,coco mademoiselle body oil,565,p116700,116700,(not set)/200 ml,fnb,1,fragrance,women,/ae-en/fragrance/p/116700/coco-mademoiselle-bo...,NaN,565,152.55
4,coco mademoiselle silky body cream,440,p116790,116790,(not set)/150 g,fnb,1,fragrance,women,/ae-en/fragrance/p/116790/coco-mademoiselle-si...,NaN,440,118.80

In [ ]:
search_query = "eau de cologne les exclusifs de chanel – eau de toilette"
result = df_clean[df_clean['product_name'].str.contains(search_query, case=False, na=False)]

if not result.empty:
    print(f"Found {len(result)} product(s) matching '{search_query}':")
    display(result)
else:
    print(f"No product found matching '{search_query}'.")

In [8]:
df_clean['sku'] = df_clean['sku'].astype(str)
df['sku'] = df['sku'].astype(str)
df_clean = df_clean.merge(df[['sku', 'image_url']], on='sku', how='left')
display(df_clean.head())

,product_name,price,product_id,sku,variant,brand,quantity,category,sub_category,product_url,image_url_x,price_aed,price_usd,image_url_y
0,coco body cream,440,p113940,113990,(not set)/150 g,fnb,1,fragrance,women,/ae-en/fragrance/p/113990/coco-body-cream/quic...,NaN,440,118.80,"https://www.chanel.com/images/t_one//w_0.51,h_..."
1,egoiste deodorant stick,210,p114700,114700,(not set)/60 g,fnb,1,fragrance,bath and body,/ae-en/fragrance/p/114700/egoiste-deodorant-st...,NaN,210,56.70,"https://www.chanel.com/images/t_one//w_0.51,h_..."
2,coco mademoiselle fragrance primer,540,p116690,116690,(not set)/100 ml,fnb,1,fragrance,women,/ae-en/fragrance/p/116690/coco-mademoiselle-fr...,NaN,540,145.80,"https://www.chanel.com/images/t_one//w_0.51,h_..."
3,coco mademoiselle body oil,565,p116700,116700,(not set)/200 ml,fnb,1,fragrance,women,/ae-en/fragrance/p/116700/coco-mademoiselle-bo...,NaN,565,152.55,"https://www.chanel.com/images/t_one//w_0.61,h_..."
4,coco mademoiselle silky body cream,440,p116790,116790,(not set)/150 g,fnb,1,fragrance,women,/ae-en/fragrance/p/116790/coco-mademoiselle-si...,NaN,440,118.80,"https://www.chanel.com/images/t_one//w_0.51,h_..."

In [9]:
# Drop the specified columns
df_clean = df_clean.drop(columns=['price', 'image_url_x'])

# Rename 'image_url_y' to 'image_url'
df_clean = df_clean.rename(columns={'image_url_y': 'image_url'})

# Add base URL to 'product_url'
df_clean['product_url'] = "https://www.chanel.com/" + df_clean['product_url']

# Display the updated DataFrame
display(df_clean.head())

,product_name,product_id,sku,variant,brand,quantity,category,sub_category,product_url,price_aed,price_usd,image_url
0,coco body cream,p113940,113990,(not set)/150 g,fnb,1,fragrance,women,https://www.chanel.com//ae-en/fragrance/p/1139...,440,118.80,"https://www.chanel.com/images/t_one//w_0.51,h_..."
1,egoiste deodorant stick,p114700,114700,(not set)/60 g,fnb,1,fragrance,bath and body,https://www.chanel.com//ae-en/fragrance/p/1147...,210,56.70,"https://www.chanel.com/images/t_one//w_0.51,h_..."
2,coco mademoiselle fragrance primer,p116690,116690,(not set)/100 ml,fnb,1,fragrance,women,https://www.chanel.com//ae-en/fragrance/p/1166...,540,145.80,"https://www.chanel.com/images/t_one//w_0.51,h_..."
3,coco mademoiselle body oil,p116700,116700,(not set)/200 ml,fnb,1,fragrance,women,https://www.chanel.com//ae-en/fragrance/p/1167...,565,152.55,"https://www.chanel.com/images/t_one//w_0.61,h_..."
4,coco mademoiselle silky body cream,p116790,116790,(not set)/150 g,fnb,1,fragrance,women,https://www.chanel.com//ae-en/fragrance/p/1167...,440,118.80,"https://www.chanel.com/images/t_one//w_0.51,h_..."

In [10]:
# Save the DataFrame to a JSON file
df_clean.to_json("final_chanel_products.json", orient="records", indent=2)

print("DataFrame successfully saved to final_chanel_products.json")

DataFrame successfully saved to final_chanel_products.json

In [11]:
# Save the DataFrame to a CSV file
df_clean.to_csv("final_chanel_products.csv", index=False)

print("DataFrame successfully saved to final_chanel_products.csv")

DataFrame successfully saved to final_chanel_products.csv

In [13]:
import requests

url = "https://www.chanel.com/ae-en/fragrance/p/102420/paris-venise-les-eaux-de-chanel-eau-de-toilette-spray/"
output_filename = "chanel_product_page.html"

# Define headers to mimic a web browser
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
}

try:
    # Pass the headers with the request
    response = requests.get(url, headers=headers)
    response.raise_for_status()  # Raise an HTTPError for bad responses (4xx or 5xx)

    with open(output_filename, "w", encoding="utf-8") as f:
        f.write(response.text)
    print(f"Successfully fetched and saved HTML from {url} to {output_filename}")
except requests.exceptions.HTTPError as errh:
    print(f"Http Error: {errh}")
except requests.exceptions.ConnectionError as errc:
    print(f"Error Connecting: {errc}")
except requests.exceptions.Timeout as errt:
    print(f"Timeout Error: {errt}")
except requests.exceptions.RequestException as err:
    print(f"Something went wrong: {err}")

Successfully fetched and saved HTML from https://www.chanel.com/ae-en/fragrance/p/102420/paris-venise-les-eaux-de-chanel-eau-de-toilette-spray/ to chanel_product_page.html

In [14]:
from bs4 import BeautifulSoup

def extract_variants_from_html_snippet(html_snippet):
    soup = BeautifulSoup(html_snippet, "html.parser")
    variants = []

    # Find the unordered list that contains the variants
    variant_list = soup.find("ul", class_="dropdown__list")

    if variant_list:
        # Find all list items representing individual variants
        variant_items = variant_list.find_all("li", class_="dropdown__list__variants")

        for item in variant_items:
            variant_data = {}
            # Extract size
            size_tag = item.find("span", class_="dropdown_size_text")
            if size_tag:
                variant_data["size"] = size_tag.get_text(strip=True).replace("\u00a0", " ") # Replace non-breaking space

            # Extract price
            price_tag = item.find("span", class_="dropdown_size_price")
            if price_tag:
                variant_data["price"] = price_tag.get_text(strip=True)

            if variant_data: # Only add if some data was extracted
                variants.append(variant_data)
    return variants

# HTML sample provided by the user
html_sample = """<ul class=\"dropdown__list\" role=\"presentation\" data-test=\"lblAllVarients\"> <li role=\"menuitem\" tabindex=\"0\" class=\"dropdown__list__variants\" aria-current=\"true\" data-test=\"btnVarientByValue\"> <a href=\"/ae-en/fragrance/p/102420/paris-venise-les-eaux-de-chanel-eau-de-toilette-spray/\" class=\"js-dropdown-item dropdown__list__item\" data-value=\"102420\"> <span data-test=\"lstFits_ByFITNAME\" class=\"dropdown_size_text\">125&nbsp;ml </span> <span class=\"dropdown_size_price\">765 AED</span> </a> </li> <li role=\"menuitem\" tabindex=\"0\" class=\"dropdown__list__variants\" data-test=\"btnVarientByValue\"> <a href=\"/ae-en/fragrance/p/102620/paris-venise-les-eaux-de-chanel-eau-de-toilette-spray/\" class=\"js-dropdown-item dropdown__list__item\" data-value=\"102620\"> <span data-test=\"lstFits_ByFITNAME\" class=\"dropdown_size_text\">50&nbsp;ml </span> <span class=\"dropdown_size_price\">530 AED</span> </a> </li> </ul>"""

# Demonstrate the function
extracted_variants = extract_variants_from_html_snippet(html_sample)
print("Extracted Variants:")
for variant in extracted_variants:
    print(variant)

Extracted Variants:
{'size': '125 ml', 'price': '765 AED'}
{'size': '50 ml', 'price': '530 AED'}

In [15]:
import os
import json
import requests
from bs4 import BeautifulSoup
from urllib.parse import urlparse

# -----------------------------
# CONFIG
# -----------------------------
OUTPUT_FOLDER = "chanel_pages"
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}

os.makedirs(OUTPUT_FOLDER, exist_ok=True)


# -----------------------------
# FETCH HTML
# -----------------------------
def fetch_and_save_html(url, sku):
    try:
        response = requests.get(url, headers=HEADERS, timeout=20)
        response.raise_for_status()

        filename = os.path.join(OUTPUT_FOLDER, f"{sku}.html")

        with open(filename, "w", encoding="utf-8") as f:
            f.write(response.text)

        return response.text

    except Exception as e:
        print(f"❌ Failed to fetch {url}: {e}")
        return None


# -----------------------------
# EXTRACT VARIANTS
# -----------------------------
def extract_variants(html):
    soup = BeautifulSoup(html, "html.parser")
    variants = []

    variant_list = soup.find("ul", class_="dropdown__list")

    if not variant_list:
        return variants

    items = variant_list.find_all("li", class_="dropdown__list__variants")

    for item in items:
        variant_data = {}

        size_tag = item.find("span", class_="dropdown_size_text")
        price_tag = item.find("span", class_="dropdown_size_price")
        link_tag = item.find("a", href=True)

        if size_tag:
            variant_data["size"] = size_tag.get_text(strip=True).replace("\xa0", " ")

        if price_tag:
            price_text = price_tag.get_text(strip=True)
            variant_data["price_aed"] = int(price_text.replace("AED", "").strip())

        if link_tag:
            variant_data["variant_url"] = "https://www.chanel.com" + link_tag["href"]

            # extract SKU from URL
            try:
                variant_data["sku"] = link_tag["href"].split("/p/")[1].split("/")[0]
            except:
                variant_data["sku"] = None

        if variant_data:
            variants.append(variant_data)

    return variants


# -----------------------------
# MAIN PROCESS
# -----------------------------
def enrich_products(input_json):
    enriched = []

    for product in input_json:
        print(f"Processing: {product['product_name']}")

        html = fetch_and_save_html(product["product_url"], product["sku"])

        if not html:
            product["variants"] = []
            enriched.append(product)
            continue

        variants = extract_variants(html)

        # attach variants
        product["variants"] = variants

        enriched.append(product)

    return enriched


# -----------------------------
# RUN
# -----------------------------
if __name__ == "__main__":

    # load your input JSON
    with open("/content/final_chanel_products.json", "r", encoding="utf-8") as f:
        products = json.load(f)

    enriched_products = enrich_products(products)

    # save updated JSON
    with open("final_chanel_products_enriched.json", "w", encoding="utf-8") as f:
        json.dump(enriched_products, f, indent=2, ensure_ascii=False)

    print("\n✅ Done! Output saved to output_enriched.json")

Processing: coco body cream
Processing: egoiste deodorant stick
Processing:  coco mademoiselle fragrance primer
Processing: coco mademoiselle body oil
Processing: coco mademoiselle silky body cream
Processing: coco mademoiselle fresh deodorant spray
Processing: coco mademoiselle gentle perfumed soap
Processing: coco mademoiselle moisturizing body lotion
Processing: coco mademoiselle foaming shower gel
Processing: coco mademoiselle hair perfume
Processing: pour monsieur deodorant stick
Processing: antaeus deodorant stick
Processing: gabrielle chanel  body oil
Processing: gabrielle chanel body cream
Processing: gabrielle chanel fragrance primer
Processing: gabrielle chanel hair mist
Processing: gabrielle chanel deodorant spray
Processing: gabrielle chanel moisturizing body lotion
Processing: gabrielle chanel foaming shower gel
Processing: allure homme after shave moisturizer
Processing: allure homme after shave lotion
Processing: allure homme deodorant stick
Processing: allure homme all-over spray
Processing: allure homme soap
Processing: amplified gaze makeup set
Processing: les essentiels coco   coco mademoiselle eau de parfum and rouge coco flash 82 live
Processing: le recourbe cils de chanel eyelash curler
Processing: les pinceaux rouge noir collection of 3 professional makeup brushes
Processing: les pinceaux de chanel sponge brush
Processing: les pinceaux de chanel dual-ended lip brush n°300
Processing: les pinceaux de chanel eye-contouring brush n°203
Processing: les pinceaux de chanel retractable dual-ended eyeshadow brush n°200
Processing: les pinceaux de chanel retractable dual-ended concealer brush n°105
Processing: les pinceaux de chanel retractable highlighter brush n°111
Processing: les pinceaux de chanel touch-up face brush n°104
Processing: les pinceaux de chanel retractable kabuki brush n°108
Processing: cc cream super active complete correction spf 50
Processing: sublimage le soin perfecteur ultimate primer: moisturizes and illuminates
Processing: sublimage l’essence de teint  ultimate serum foundation: unifies and enhances
Processing: les 9 ombres high intensity eyeshadow palette
Processing: rouge coco gloss moisturizing glossimer
Processing: rouge allure laque ultrawear shine liquid lip colour
Processing: baume essentiel multi-use glow stick
Processing: 31 le rouge satin lipstick
Processing: 31 le rouge matte lipstick
Processing: le rouge duo ultra tenue ultrawear liquid lip colour

KeyboardInterrupt:

In [16]:
import os
import json
import requests
from bs4 import BeautifulSoup
from concurrent.futures import ThreadPoolExecutor, as_completed

# -----------------------------
# CONFIG
# -----------------------------
OUTPUT_FOLDER = "chanel_pages"
MAX_WORKERS = 10  # adjust (10–20 is usually safe)

os.makedirs(OUTPUT_FOLDER, exist_ok=True)

session = requests.Session()
session.headers.update({
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
})


# -----------------------------
# FETCH HTML
# -----------------------------
def fetch_and_save_html(url, sku):
    try:
        response = session.get(url, timeout=20)
        response.raise_for_status()

        filename = os.path.join(OUTPUT_FOLDER, f"{sku}.html")

        with open(filename, "w", encoding="utf-8") as f:
            f.write(response.text)

        return response.text

    except Exception as e:
        print(f"❌ Failed: {sku} → {e}")
        return None


# -----------------------------
# EXTRACT VARIANTS
# -----------------------------
def extract_variants(html):
    soup = BeautifulSoup(html, "html.parser")
    variants = []

    variant_list = soup.find("ul", class_="dropdown__list")
    if not variant_list:
        return variants

    items = variant_list.find_all("li", class_="dropdown__list__variants")

    for item in items:
        variant_data = {}

        size_tag = item.find("span", class_="dropdown_size_text")
        price_tag = item.find("span", class_="dropdown_size_price")
        link_tag = item.find("a", href=True)

        if size_tag:
            variant_data["size"] = size_tag.get_text(strip=True).replace("\xa0", " ")

        if price_tag:
            try:
                variant_data["price_aed"] = int(
                    price_tag.get_text(strip=True).replace("AED", "").strip()
                )
            except:
                variant_data["price_aed"] = None

        if link_tag:
            href = link_tag["href"]
            variant_data["variant_url"] = "https://www.chanel.com" + href

            try:
                variant_data["sku"] = href.split("/p/")[1].split("/")[0]
            except:
                variant_data["sku"] = None

        if variant_data:
            variants.append(variant_data)

    return variants


# -----------------------------
# PROCESS SINGLE PRODUCT
# -----------------------------
def process_product(product):
    sku = product.get("sku")
    url = product.get("product_url")

    print(f"Processing: {sku}")

    html = fetch_and_save_html(url, sku)

    if not html:
        product["variants"] = []
        return product

    variants = extract_variants(html)
    product["variants"] = variants

    return product


# -----------------------------
# MAIN PARALLEL PROCESS
# -----------------------------
def enrich_products_parallel(products):
    results = []

    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = [executor.submit(process_product, p) for p in products]

        for future in as_completed(futures):
            try:
                result = future.result()
                results.append(result)
            except Exception as e:
                print(f"❌ Error in thread: {e}")

    return results


# -----------------------------
# RUN
# -----------------------------
if __name__ == "__main__":

    with open("/content/final_chanel_products.json", "r", encoding="utf-8") as f:
        products = json.load(f)

    enriched_products = enrich_products_parallel(products)

    with open("final_chanel_products_enriched.json", "w", encoding="utf-8") as f:
        json.dump(enriched_products, f, indent=2, ensure_ascii=False)

    print(f"\n✅ Done! Processed {len(enriched_products)} products")

Processing: 113990
Processing: 114700
Processing: 116690
Processing: 116700
Processing: 116790
Processing: 116860
Processing: 116900
Processing: 116945
Processing: 116965
Processing: 116997
Processing: 117921
Processing: 118700
Processing: 120820
Processing: 120830
Processing: 120840
Processing: 120870
Processing: 120930
Processing: 120940Processing: 120960

Processing: 121250
Processing: 121270
Processing: 121700
Processing: 121820
Processing: 121880
Processing: 101096
Processing: 101118
Processing: 137880
Processing: 138177
Processing: 138830
Processing: 138854
Processing: 138855
Processing: 138857
Processing: 138858
Processing: 138859
Processing: 138860
Processing: 138861
Processing: 140570
Processing: 144270
Processing: 147140
Processing: 148847
Processing: 156716
Processing: 165083
Processing: 169060
Processing: 171542
Processing: 171838
Processing: 175174
Processing: 183802
Processing: 186362
Processing: 133040
Processing: 133070
Processing: 133510
Processing: 133520
Processing: 133650
Processing: 133860
Processing: 140650
Processing: 140670
Processing: 140730
Processing: 141020
Processing: 141040
Processing: 141050
Processing: 141370
Processing: 141390
Processing: 141415
Processing: 141640
Processing: 141660
Processing: 141670
Processing: 141690
Processing: 143170
Processing: 144330
Processing: 144350
Processing: 144360
Processing: 144940
Processing: 133635
Processing: 140025
Processing: 140045
Processing: 140055
Processing: 140665
Processing: 140680
Processing: 141175
Processing: 144865
Processing: 144875
Processing: 147545
Processing: 147555
Processing: 147905
Processing: 171900
Processing: 171918
Processing: 172734
Processing: 173018
Processing: 175028
Processing: 178012
Processing: 178072
Processing: 181014
Processing: 181220
Processing: 181234
Processing: 182450
Processing: 183015
Processing: 184566
Processing: 184764
Processing: 184930
Processing: 185388
Processing: 186330
Processing: 186926
Processing: 187542
Processing: 187546
Processing: 187615
Processing: 191158
Processing: 191310
Processing: 191410
Processing: 102020
Processing: 102030
Processing: 102040
Processing: 102050
Processing: 133120
Processing: 133130
Processing: 133230
Processing: 133630
Processing: 140040
Processing: 140190
Processing: 140640
Processing: 140660
Processing: 140700
Processing: 141090
Processing: 141680
Processing: 141897
Processing: 141900
Processing: 141910
Processing: 143120
❌ Failed: 183015 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 144980
Processing: 147565
Processing: 147595
Processing: 147900
Processing: 101565
Processing: 102400
❌ Failed: 184566 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 102410
❌ Failed: 133230 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 102420
❌ Failed: 102050 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 113551
Processing: 113660
❌ Failed: 141680 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 114460
❌ Failed: 143120 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 115690
❌ Failed: 144980 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 117460
Processing: 118460
Processing: 119490
❌ Failed: 147595 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 119530
❌ Failed: 147565 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 119690
Processing: 120360
Processing: 120525
Processing: 120630
❌ Failed: 101565 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 121460
Processing: 123460
Processing: 124460
Processing: 127451
Processing: 127460
❌ Failed: 102400 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 129460
Processing: 129730
Processing: 135690
Processing: 101113
Processing: 101117
Processing: 101120
Processing: 101156
Processing: 105500
Processing: 107300
❌ Failed: 102410 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 107464
❌ Failed: 114460 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 111690
❌ Failed: 115690 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 112460
Processing: 112530
Processing: 113530
❌ Failed: 127451 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 116310
❌ Failed: 124460 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 116400
❌ Failed: 101120 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 120400
Processing: 120800
❌ Failed: 101156 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 123300
❌ Failed: 105500 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 123500
Processing: 123800
❌ Failed: 107300 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 125407
❌ Failed: 107464 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 125450
Processing: 126100
Processing: 126300
Processing: 136100
Processing: 105580
Processing: 105700
Processing: 105728
Processing: 105738
Processing: 105748
Processing: 105765
Processing: 105798
Processing: 105820
Processing: 107070Processing: 107520

Processing: 107580
Processing: 107710
Processing: 107930
Processing: 107960
Processing: 107970
Processing: 107980
Processing: 112940
Processing: 112990
Processing: 113730
Processing: 113740
Processing: 113850
Processing: 126110
Processing: 126305
Processing: 136110
Processing: 101126
Processing: 151019
Processing: 151029
Processing: 151477
Processing: 151578
Processing: 151799
Processing: 151819
Processing: 153156
Processing: 158810
Processing: 174203
Processing: 179419
Processing: 179435
Processing: 179443
Processing: 182212
Processing: 182350
Processing: 183750
Processing: 184012
Processing: 184199
Processing: 184219
Processing: 187098Processing: 188212

Processing: 190097
Processing: 191710
Processing: 196110
Processing: 105680
Processing: 107180
Processing: 107230
Processing: 107360
Processing: 116260
Processing: 116437
Processing: 116438
Processing: 116460
Processing: 116520
Processing: 116660
Processing: 116959
Processing: 123320
Processing: 123410
Processing: 123560
Processing: 123630
Processing: 125530
Processing: 126260
Processing: 126320
Processing: 126460
❌ Failed: 188212 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 126520
Processing: 126560
Processing: 136150
Processing: 136220
Processing: 136420
Processing: 138842
❌ Failed: 116460 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 138843
Processing: 138856
❌ Failed: 116520 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 144790
Processing: 144930
Processing: 145181
Processing: 145385
Processing: 145764
Processing: 146314
Processing: 148030
Processing: 151209
Processing: 151457
Processing: 156774
Processing: 160990
Processing: 162387
Processing: 162580
Processing: 163854
Processing: 164202
Processing: 165167
❌ Failed: 138843 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 168242
Processing: 168640
Processing: 171226
Processing: 171509
Processing: 171752Processing: 102430

Processing: 102440
Processing: 102747
Processing: 105340
Processing: 105530
Processing: 107460
Processing: 122210
Processing: 122220
❌ Failed: 165167 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 122230
❌ Failed: 171226 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 122240
❌ Failed: 171509 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 122250
❌ Failed: 102430 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 122260
❌ Failed: 102440 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 122270
❌ Failed: 105340 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 122280
Processing: 122290
❌ Failed: 105530 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 122300
Processing: 122310
Processing: 122320
Processing: 122330
Processing: 122340
Processing: 122350
Processing: 122360
Processing: 122380
Processing: 122560
Processing: 133060
Processing: 140020
Processing: 140050
Processing: 140070
❌ Failed: 122230 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 140240
❌ Failed: 122250 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 140290
❌ Failed: 122290 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 141030
Processing: 141070
Processing: 141170
Processing: 141490
Processing: 141740
Processing: 141760
Processing: 141770
Processing: 141790
Processing: 141810
Processing: 141846
Processing: 141960
Processing: 143030
❌ Failed: 122360 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 144010
Processing: 144290
❌ Failed: 122380 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 147450
❌ Failed: 140050 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 147540
Processing: 147590
❌ Failed: 141070 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 147960
❌ Failed: 141030 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 130410
Processing: 131882
Processing: 132726
Processing: 134670
Processing: 138841
❌ Failed: 143030 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 138844
Processing: 138845
Processing: 138846
Processing: 138847
Processing: 138848
Processing: 138849
❌ Failed: 130410 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 138850
Processing: 138851
Processing: 138852
Processing: 138853
❌ Failed: 138847 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 151948
❌ Failed: 138848 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 151997
❌ Failed: 138844 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 162357
❌ Failed: 138841 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 181257
❌ Failed: 138849 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 190067
❌ Failed: 131882 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 192410
❌ Failed: 138850 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 194210
❌ Failed: 138851 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 195710
❌ Failed: 138852 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 195810
❌ Failed: 138853 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 101735
Processing: 105848
Processing: 116958
Processing: 120850
Processing: 123250
❌ Failed: 151948 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 123270
Processing: 123700
❌ Failed: 151997 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 123710
Processing: 123730
Processing: 123930
Processing: 124060
Processing: 124700
❌ Failed: 162357 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 124930
❌ Failed: 190067 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 126720
Processing: 126760
❌ Failed: 181257 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 126810
Processing: 126990
❌ Failed: 123250 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 136270
❌ Failed: 123710 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 136290
❌ Failed: 123730 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 136849
❌ Failed: 124930 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 136850
❌ Failed: 123930 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 136880
❌ Failed: 124060 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 136980
❌ Failed: 126810 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 136990
❌ Failed: 126720 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 105490
❌ Failed: 126760 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 105505
Processing: 105550
Processing: 105571
Processing: 107125
❌ Failed: 136290 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 107310
❌ Failed: 136850 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 107810
❌ Failed: 136980 → HTTPSConnectionPool(host='www.chanel.com', port=443): Read timed out. (read timeout=20)
Processing: 116040
Processing: 116090
Processing: 116320
Processing: 116410
Processing: 116610
Processing: 120410
Processing: 120450
Processing: 120659
Processing: 120810
Processing: 123810
Processing: 125110
Processing: 125410
Processing: 125470
Processing: 101153
Processing: 133140
Processing: 133225
Processing: 133325
Processing: 133330
Processing: 133337
Processing: 133350
Processing: 133355
Processing: 133360
Processing: 133365
Processing: 133537
Processing: 133850
Processing: 133857
Processing: 140030
Processing: 140046
Processing: 140895
Processing: 141780
Processing: 144860
Processing: 144870
Processing: 144890
Processing: 147550
Processing: 147560
Processing: 147570Processing: 147575

Processing: 132812
Processing: 155724
Processing: 158255
Processing: 158260
Processing: 158368
Processing: 158910
Processing: 162854
Processing: 173542
Processing: 173854
Processing: 175435
Processing: 179105
Processing: 179111
Processing: 179113
Processing: 179121
Processing: 179123
Processing: 179125
Processing: 179127
Processing: 179129
Processing: 179131
Processing: 179135
Processing: 179137
Processing: 185272
Processing: 132212
Processing: 132400
Processing: 137500
Processing: 138840
Processing: 169097
Processing: 179139
Processing: 179143
Processing: 179147
Processing: 179151
Processing: 179153
Processing: 179155
Processing: 179157
Processing: 179161
Processing: 179173
Processing: 179175
Processing: 179183
Processing: 179195
Processing: 179371
Processing: 179377
Processing: 179387
Processing: 179397
Processing: 185872
Processing: 190250

✅ Done! Processed 459 products

In [17]:
!zip -r chanel_pages.zip /content/chanel_pages

  adding: content/chanel_pages/ (stored 0%)
  adding: content/chanel_pages/147555.html (deflated 97%)
  adding: content/chanel_pages/136110.html (deflated 97%)
  adding: content/chanel_pages/140895.html (deflated 97%)
  adding: content/chanel_pages/121460.html (deflated 97%)
  adding: content/chanel_pages/179137.html (deflated 97%)
  adding: content/chanel_pages/102040.html (deflated 97%)
  adding: content/chanel_pages/122320.html (deflated 97%)
  adding: content/chanel_pages/185272.html (deflated 97%)
  adding: content/chanel_pages/132212.html (deflated 97%)
  adding: content/chanel_pages/133650.html (deflated 97%)
  adding: content/chanel_pages/120930.html (deflated 97%)
  adding: content/chanel_pages/179387.html (deflated 97%)
  adding: content/chanel_pages/120360.html (deflated 97%)
  adding: content/chanel_pages/141390.html (deflated 97%)
  adding: content/chanel_pages/113660.html (deflated 97%)
  adding: content/chanel_pages/140025.html (deflated 97%)
  adding: content/chanel_pages/151819.html (deflated 97%)
  adding: content/chanel_pages/107580.html (deflated 97%)
  adding: content/chanel_pages/195810.html (deflated 97%)
  adding: content/chanel_pages/133860.html (deflated 97%)
  adding: content/chanel_pages/107310.html (deflated 97%)
  adding: content/chanel_pages/116997.html (deflated 97%)
  adding: content/chanel_pages/132726.html (deflated 97%)
  adding: content/chanel_pages/191310.html (deflated 97%)
  adding: content/chanel_pages/116900.html (deflated 97%)
  adding: content/chanel_pages/107230.html (deflated 97%)
  adding: content/chanel_pages/140670.html (deflated 97%)
  adding: content/chanel_pages/137880.html (deflated 97%)
  adding: content/chanel_pages/133225.html (deflated 97%)
  adding: content/chanel_pages/120940.html (deflated 97%)
  adding: content/chanel_pages/116790.html (deflated 97%)
  adding: content/chanel_pages/179113.html (deflated 97%)
  adding: content/chanel_pages/144290.html (deflated 97%)
  adding: content/chanel_pages/141640.html (deflated 97%)
  adding: content/chanel_pages/147540.html (deflated 97%)
  adding: content/chanel_pages/171752.html (deflated 97%)
  adding: content/chanel_pages/112460.html (deflated 97%)
  adding: content/chanel_pages/138857.html (deflated 97%)
  adding: content/chanel_pages/141900.html (deflated 97%)
  adding: content/chanel_pages/133130.html (deflated 97%)
  adding: content/chanel_pages/113530.html (deflated 97%)
  adding: content/chanel_pages/127460.html (deflated 97%)
  adding: content/chanel_pages/140700.html (deflated 97%)
  adding: content/chanel_pages/133857.html (deflated 97%)
  adding: content/chanel_pages/133040.html (deflated 97%)
  adding: content/chanel_pages/185872.html (deflated 97%)
  adding: content/chanel_pages/132400.html (deflated 97%)
  adding: content/chanel_pages/120410.html (deflated 97%)
  adding: content/chanel_pages/151799.html (deflated 97%)
  adding: content/chanel_pages/183750.html (deflated 97%)
  adding: content/chanel_pages/141846.html (deflated 97%)
  adding: content/chanel_pages/105728.html (deflated 97%)
  adding: content/chanel_pages/147575.html (deflated 97%)
  adding: content/chanel_pages/186926.html (deflated 97%)
  adding: content/chanel_pages/133630.html (deflated 97%)
  adding: content/chanel_pages/134670.html (deflated 97%)
  adding: content/chanel_pages/147900.html (deflated 97%)
  adding: content/chanel_pages/126320.html (deflated 97%)
  adding: content/chanel_pages/101096.html (deflated 83%)
  adding: content/chanel_pages/116400.html (deflated 97%)
  adding: content/chanel_pages/144890.html (deflated 97%)
  adding: content/chanel_pages/105798.html (deflated 97%)
  adding: content/chanel_pages/126305.html (deflated 97%)
  adding: content/chanel_pages/179135.html (deflated 97%)
  adding: content/chanel_pages/121700.html (deflated 97%)
  adding: content/chanel_pages/140240.html (deflated 97%)
  adding: content/chanel_pages/113850.html (deflated 97%)
  adding: content/chanel_pages/126260.html (deflated 97%)
  adding: content/chanel_pages/136849.html (deflated 82%)
  adding: content/chanel_pages/126110.html (deflated 97%)
  adding: content/chanel_pages/136220.html (deflated 97%)
  adding: content/chanel_pages/101735.html (deflated 97%)
  adding: content/chanel_pages/184012.html (deflated 97%)
  adding: content/chanel_pages/140680.html (deflated 97%)
  adding: content/chanel_pages/133537.html (deflated 97%)
  adding: content/chanel_pages/116958.html (deflated 97%)
  adding: content/chanel_pages/117460.html (deflated 97%)
  adding: content/chanel_pages/107360.html (deflated 97%)
  adding: content/chanel_pages/123560.html (deflated 97%)
  adding: content/chanel_pages/175435.html (deflated 97%)
  adding: content/chanel_pages/141690.html (deflated 97%)
  adding: content/chanel_pages/105700.html (deflated 97%)
  adding: content/chanel_pages/120830.html (deflated 97%)
  adding: content/chanel_pages/179105.html (deflated 97%)
  adding: content/chanel_pages/138858.html (deflated 97%)
  adding: content/chanel_pages/120870.html (deflated 97%)
  adding: content/chanel_pages/120659.html (deflated 97%)
  adding: content/chanel_pages/141490.html (deflated 97%)
  adding: content/chanel_pages/140660.html (deflated 97%)
  adding: content/chanel_pages/118700.html (deflated 97%)
  adding: content/chanel_pages/179157.html (deflated 97%)
  adding: content/chanel_pages/107180.html (deflated 97%)
  adding: content/chanel_pages/116437.html (deflated 97%)
  adding: content/chanel_pages/191410.html (deflated 97%)
  adding: content/chanel_pages/140665.html (deflated 97%)
  adding: content/chanel_pages/102747.html (deflated 97%)
  adding: content/chanel_pages/113730.html (deflated 97%)
  adding: content/chanel_pages/179147.html (deflated 97%)
  adding: content/chanel_pages/144360.html (deflated 97%)
  adding: content/chanel_pages/117921.html (deflated 97%)
  adding: content/chanel_pages/119530.html (deflated 97%)
  adding: content/chanel_pages/122280.html (deflated 97%)
  adding: content/chanel_pages/147570.html (deflated 97%)
  adding: content/chanel_pages/116040.html (deflated 97%)
  adding: content/chanel_pages/187615.html (deflated 97%)
  adding: content/chanel_pages/136150.html (deflated 97%)
  adding: content/chanel_pages/111690.html (deflated 97%)
  adding: content/chanel_pages/158368.html (deflated 97%)
  adding: content/chanel_pages/138859.html (deflated 97%)
  adding: content/chanel_pages/147550.html (deflated 97%)
  adding: content/chanel_pages/181234.html (deflated 97%)
  adding: content/chanel_pages/116610.html (deflated 97%)
  adding: content/chanel_pages/120840.html (deflated 97%)
  adding: content/chanel_pages/144010.html (deflated 97%)
  adding: content/chanel_pages/171900.html (deflated 97%)
  adding: content/chanel_pages/171838.html (deflated 97%)
  adding: content/chanel_pages/184199.html (deflated 97%)
  adding: content/chanel_pages/140040.html (deflated 97%)
  adding: content/chanel_pages/141810.html (deflated 97%)
  adding: content/chanel_pages/120810.html (deflated 97%)
  adding: content/chanel_pages/138854.html (deflated 97%)
  adding: content/chanel_pages/184219.html (deflated 97%)
  adding: content/chanel_pages/141020.html (deflated 97%)
  adding: content/chanel_pages/141780.html (deflated 97%)
  adding: content/chanel_pages/141897.html (deflated 97%)
  adding: content/chanel_pages/101118.html (deflated 97%)
  adding: content/chanel_pages/133337.html (deflated 97%)
  adding: content/chanel_pages/141170.html (deflated 97%)
  adding: content/chanel_pages/195710.html (deflated 97%)
  adding: content/chanel_pages/140650.html (deflated 97%)
  adding: content/chanel_pages/158260.html (deflated 97%)
  adding: content/chanel_pages/179127.html (deflated 97%)
  adding: content/chanel_pages/133520.html (deflated 97%)
  adding: content/chanel_pages/122330.html (deflated 97%)
  adding: content/chanel_pages/179131.html (deflated 97%)
  adding: content/chanel_pages/107710.html (deflated 97%)
  adding: content/chanel_pages/179139.html (deflated 97%)
  adding: content/chanel_pages/141910.html (deflated 97%)
  adding: content/chanel_pages/140290.html (deflated 97%)
  adding: content/chanel_pages/136880.html (deflated 97%)
  adding: content/chanel_pages/123800.html (deflated 97%)
  adding: content/chanel_pages/132812.html (deflated 97%)
  adding: content/chanel_pages/151578.html (deflated 97%)
  adding: content/chanel_pages/102030.html (deflated 97%)
  adding: content/chanel_pages/144860.html (deflated 97%)
  adding: content/chanel_pages/160990.html (deflated 97%)
  adding: content/chanel_pages/144790.html (deflated 97%)
  adding: content/chanel_pages/121880.html (deflated 97%)
  adding: content/chanel_pages/140030.html (deflated 97%)
  adding: content/chanel_pages/179161.html (deflated 97%)
  adding: content/chanel_pages/153156.html (deflated 97%)
  adding: content/chanel_pages/122560.html (deflated 97%)
  adding: content/chanel_pages/105505.html (deflated 97%)
  adding: content/chanel_pages/107980.html (deflated 97%)
  adding: content/chanel_pages/144940.html (deflated 97%)
  adding: content/chanel_pages/141790.html (deflated 97%)
  adding: content/chanel_pages/123410.html (deflated 97%)
  adding: content/chanel_pages/162580.html (deflated 97%)
  adding: content/chanel_pages/125470.html (deflated 97%)
  adding: content/chanel_pages/179173.html (deflated 97%)
  adding: content/chanel_pages/107460.html (deflated 97%)
  adding: content/chanel_pages/138855.html (deflated 97%)
  adding: content/chanel_pages/133325.html (deflated 97%)
  adding: content/chanel_pages/116945.html (deflated 97%)
  adding: content/chanel_pages/184764.html (deflated 97%)
  adding: content/chanel_pages/143170.html (deflated 97%)
  adding: content/chanel_pages/122340.html (deflated 97%)
  adding: content/chanel_pages/158810.html (deflated 97%)
  adding: content/chanel_pages/169097.html (deflated 97%)
  adding: content/chanel_pages/164202.html (deflated 97%)
  adding: content/chanel_pages/113551.html (deflated 97%)
  adding: content/chanel_pages/133060.html (deflated 97%)
  adding: content/chanel_pages/105550.html (deflated 97%)
  adding: content/chanel_pages/179153.html (deflated 97%)
  adding: content/chanel_pages/175174.html (deflated 97%)
  adding: content/chanel_pages/190250.html (deflated 97%)
  adding: content/chanel_pages/122300.html (deflated 97%)
  adding: content/chanel_pages/126460.html (deflated 97%)
  adding: content/chanel_pages/144350.html (deflated 97%)
  adding: content/chanel_pages/141370.html (deflated 97%)
  adding: content/chanel_pages/141770.html (deflated 97%)
  adding: content/chanel_pages/129730.html (deflated 97%)
  adding: content/chanel_pages/122350.html (deflated 97%)
  adding: content/chanel_pages/101117.html (deflated 84%)
  adding: content/chanel_pages/144865.html (deflated 97%)
  adding: content/chanel_pages/145764.html (deflated 97%)
  adding: content/chanel_pages/123500.html (deflated 97%)
  adding: content/chanel_pages/126300.html (deflated 97%)
  adding: content/chanel_pages/105848.html (deflated 97%)
  adding: content/chanel_pages/158910.html (deflated 97%)
  adding: content/chanel_pages/179443.html (deflated 97%)
  adding: content/chanel_pages/181220.html (deflated 97%)
  adding: content/chanel_pages/138177.html (deflated 97%)
  adding: content/chanel_pages/121270.html (deflated 97%)
  adding: content/chanel_pages/182450.html (deflated 97%)
  adding: content/chanel_pages/147590.html (deflated 97%)
  adding: content/chanel_pages/140640.html (deflated 97%)
  adding: content/chanel_pages/118460.html (deflated 97%)
  adding: content/chanel_pages/107810.html (deflated 97%)
  adding: content/chanel_pages/120630.html (deflated 97%)
  adding: content/chanel_pages/107930.html (deflated 97%)
  adding: content/chanel_pages/123810.html (deflated 97%)
  adding: content/chanel_pages/140570.html (deflated 97%)
  adding: content/chanel_pages/105571.html (deflated 97%)
  adding: content/chanel_pages/126560.html (deflated 97%)
  adding: content/chanel_pages/121820.html (deflated 97%)
  adding: content/chanel_pages/141415.html (deflated 97%)
  adding: content/chanel_pages/144270.html (deflated 97%)
  adding: content/chanel_pages/116320.html (deflated 97%)
  adding: content/chanel_pages/120960.html (deflated 97%)
  adding: content/chanel_pages/151019.html (deflated 97%)
  adding: content/chanel_pages/144870.html (deflated 97%)
  adding: content/chanel_pages/116959.html (deflated 97%)
  adding: content/chanel_pages/122260.html (deflated 97%)
  adding: content/chanel_pages/141670.html (deflated 97%)
  adding: content/chanel_pages/120450.html (deflated 97%)
  adding: content/chanel_pages/138840.html (deflated 97%)
  adding: content/chanel_pages/187546.html (deflated 97%)
  adding: content/chanel_pages/196110.html (deflated 97%)
  adding: content/chanel_pages/191710.html (deflated 97%)
  adding: content/chanel_pages/140070.html (deflated 97%)
  adding: content/chanel_pages/125450.html (deflated 97%)
  adding: content/chanel_pages/120525.html (deflated 97%)
  adding: content/chanel_pages/120400.html (deflated 97%)
  adding: content/chanel_pages/187098.html (deflated 97%)
  adding: content/chanel_pages/125530.html (deflated 97%)
  adding: content/chanel_pages/116090.html (deflated 97%)
  adding: content/chanel_pages/186362.html (deflated 97%)
  adding: content/chanel_pages/107970.html (deflated 97%)
  adding: content/chanel_pages/136990.html (deflated 97%)
  adding: content/chanel_pages/182350.html (deflated 97%)
  adding: content/chanel_pages/165083.html (deflated 97%)
  adding: content/chanel_pages/144875.html (deflated 97%)
  adding: content/chanel_pages/162387.html (deflated 97%)
  adding: content/chanel_pages/187542.html (deflated 97%)
  adding: content/chanel_pages/136420.html (deflated 97%)
  adding: content/chanel_pages/145181.html (deflated 97%)
  adding: content/chanel_pages/162854.html (deflated 97%)
  adding: content/chanel_pages/140730.html (deflated 97%)
  adding: content/chanel_pages/171918.html (deflated 97%)
  adding: content/chanel_pages/105765.html (deflated 97%)
  adding: content/chanel_pages/141740.html (deflated 97%)
  adding: content/chanel_pages/179371.html (deflated 97%)
  adding: content/chanel_pages/181014.html (deflated 97%)
  adding: content/chanel_pages/113990.html (deflated 97%)
  adding: content/chanel_pages/151477.html (deflated 97%)
  adding: content/chanel_pages/101126.html (deflated 97%)
  adding: content/chanel_pages/179129.html (deflated 97%)
  adding: content/chanel_pages/114700.html (deflated 97%)
  adding: content/chanel_pages/119690.html (deflated 97%)
  adding: content/chanel_pages/173854.html (deflated 97%)
  adding: content/chanel_pages/158255.html (deflated 97%)
  adding: content/chanel_pages/112530.html (deflated 97%)
  adding: content/chanel_pages/133355.html (deflated 97%)
  adding: content/chanel_pages/137500.html (deflated 97%)
  adding: content/chanel_pages/147545.html (deflated 97%)
  adding: content/chanel_pages/105680.html (deflated 97%)
  adding: content/chanel_pages/141760.html (deflated 97%)
  adding: content/chanel_pages/138860.html (deflated 97%)
  adding: content/chanel_pages/179419.html (deflated 97%)
  adding: content/chanel_pages/133120.html (deflated 97%)
  adding: content/chanel_pages/179121.html (deflated 97%)
  adding: content/chanel_pages/179155.html (deflated 97%)
  adding: content/chanel_pages/146314.html (deflated 97%)
  adding: content/chanel_pages/173542.html (deflated 97%)
  adding: content/chanel_pages/122210.html (deflated 97%)
  adding: content/chanel_pages/133140.html (deflated 97%)
  adding: content/chanel_pages/194210.html (deflated 97%)
  adding: content/chanel_pages/179151.html (deflated 97%)
  adding: content/chanel_pages/105748.html (deflated 97%)
  adding: content/chanel_pages/102420.html (deflated 97%)
  adding: content/chanel_pages/135690.html (deflated 97%)
  adding: content/chanel_pages/144930.html (deflated 97%)
  adding: content/chanel_pages/122310.html (deflated 97%)
  adding: content/chanel_pages/185388.html (deflated 97%)
  adding: content/chanel_pages/116660.html (deflated 97%)
  adding: content/chanel_pages/112990.html (deflated 97%)
  adding: content/chanel_pages/179397.html (deflated 97%)
  adding: content/chanel_pages/133070.html (deflated 97%)
  adding: content/chanel_pages/105580.html (deflated 97%)
  adding: content/chanel_pages/125407.html (deflated 97%)
  adding: content/chanel_pages/140055.html (deflated 97%)
  adding: content/chanel_pages/122270.html (deflated 97%)
  adding: content/chanel_pages/133360.html (deflated 97%)
  adding: content/chanel_pages/121250.html (deflated 97%)
  adding: content/chanel_pages/136100.html (deflated 97%)
  adding: content/chanel_pages/155724.html (deflated 97%)
  adding: content/chanel_pages/126100.html (deflated 97%)
  adding: content/chanel_pages/151457.html (deflated 97%)
  adding: content/chanel_pages/107070.html (deflated 97%)
  adding: content/chanel_pages/120820.html (deflated 97%)
  adding: content/chanel_pages/123700.html (deflated 97%)
  adding: content/chanel_pages/133330.html (deflated 97%)
  adding: content/chanel_pages/133350.html (deflated 97%)
  adding: content/chanel_pages/156716.html (deflated 97%)
  adding: content/chanel_pages/105738.html (deflated 97%)
  adding: content/chanel_pages/151209.html (deflated 97%)
  adding: content/chanel_pages/169060.html (deflated 97%)
  adding: content/chanel_pages/168640.html (deflated 97%)
  adding: content/chanel_pages/179111.html (deflated 97%)
  adding: content/chanel_pages/141090.html (deflated 97%)
  adding: content/chanel_pages/107960.html (deflated 97%)
  adding: content/chanel_pages/174203.html (deflated 97%)
  adding: content/chanel_pages/112940.html (deflated 97%)
  adding: content/chanel_pages/141040.html (deflated 97%)
  adding: content/chanel_pages/123300.html (deflated 97%)
  adding: content/chanel_pages/141960.html (deflated 97%)
  adding: content/chanel_pages/140190.html (deflated 97%)
  adding: content/chanel_pages/113740.html (deflated 97%)
  adding: content/chanel_pages/126520.html (deflated 97%)
  adding: content/chanel_pages/168242.html (deflated 97%)
  adding: content/chanel_pages/126990.html (deflated 97%)
  adding: content/chanel_pages/179435.html (deflated 97%)
  adding: content/chanel_pages/125410.html (deflated 97%)
  adding: content/chanel_pages/101113.html (deflated 97%)
  adding: content/chanel_pages/116965.html (deflated 97%)
  adding: content/chanel_pages/183802.html (deflated 97%)
  adding: content/chanel_pages/133635.html (deflated 97%)
  adding: content/chanel_pages/179125.html (deflated 97%)
  adding: content/chanel_pages/191158.html (deflated 97%)
  adding: content/chanel_pages/140046.html (deflated 83%)
  adding: content/chanel_pages/147905.html (deflated 97%)
  adding: content/chanel_pages/179195.html (deflated 97%)
  adding: content/chanel_pages/156774.html (deflated 97%)
  adding: content/chanel_pages/107125.html (deflated 97%)
  adding: content/chanel_pages/141175.html (deflated 97%)
  adding: content/chanel_pages/133365.html (deflated 97%)
  adding: content/chanel_pages/179183.html (deflated 97%)
  adding: content/chanel_pages/138856.html (deflated 97%)
  adding: content/chanel_pages/138861.html (deflated 97%)
  adding: content/chanel_pages/190097.html (deflated 97%)
  adding: content/chanel_pages/144330.html (deflated 97%)
  adding: content/chanel_pages/138846.html (deflated 97%)
  adding: content/chanel_pages/145385.html (deflated 97%)
  adding: content/chanel_pages/141050.html (deflated 97%)
  adding: content/chanel_pages/175028.html (deflated 97%)
  adding: content/chanel_pages/140045.html (deflated 97%)
  adding: content/chanel_pages/122220.html (deflated 97%)
  adding: content/chanel_pages/102020.html (deflated 97%)
  adding: content/chanel_pages/119490.html (deflated 97%)
  adding: content/chanel_pages/116438.html (deflated 97%)
  adding: content/chanel_pages/138830.html (deflated 97%)
  adding: content/chanel_pages/172734.html (deflated 97%)
  adding: content/chanel_pages/171542.html (deflated 97%)