In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Upwork/mahmoud/april/moustaphalabban_products.csv')
display(df.head())

,product_id,title,handle,description,created_at,vendor,type,price,compare_at_price,available,variant_id,variant_title,variant_sku,variant_available,variant_name,variant_price,variant_compare_at_price,variant_barcode,variant_image
0,10162396299396,Pupa Wonder Me Shiny Bronzer,pupa-wonder-me-shiny-bronzer,"<p>Recreates a natural tan effect, warming and...",2025-11-08T00:55:06+02:00,Pupa,Makeup,2320,2900.0,True,51266399502468,001 Light Neutral,721050244A001,True,Pupa Wonder Me Shiny Bronzer - 001 Light Neutral,2320,2900.0,8011607401284,https://cdn.shopify.com/s/files/1/0377/3258/15...
1,10162396299396,Pupa Wonder Me Shiny Bronzer,pupa-wonder-me-shiny-bronzer,"<p>Recreates a natural tan effect, warming and...",2025-11-08T00:55:06+02:00,Pupa,Makeup,2320,2900.0,True,51266399535236,002 Medium Warm,721050244A002,True,Pupa Wonder Me Shiny Bronzer - 002 Medium Warm,2320,2900.0,8011607401291,https://cdn.shopify.com/s/files/1/0377/3258/15...
2,10162396299396,Pupa Wonder Me Shiny Bronzer,pupa-wonder-me-shiny-bronzer,"<p>Recreates a natural tan effect, warming and...",2025-11-08T00:55:06+02:00,Pupa,Makeup,2320,2900.0,True,51266399568004,003 Medium Neutral,721050244A003,True,Pupa Wonder Me Shiny Bronzer - 003 Medium Neutral,2320,2900.0,8011607401307,https://cdn.shopify.com/s/files/1/0377/3258/15...
3,10162396299396,Pupa Wonder Me Shiny Bronzer,pupa-wonder-me-shiny-bronzer,"<p>Recreates a natural tan effect, warming and...",2025-11-08T00:55:06+02:00,Pupa,Makeup,2320,2900.0,True,51266399600772,004 Dark Warm,721050244A004,True,Pupa Wonder Me Shiny Bronzer - 004 Dark Warm,2320,2900.0,8011607401314,https://cdn.shopify.com/s/files/1/0377/3258/15...
4,7203500097668,Pupa Wonder Me Blush,pupa-wonder-me-blush,<p>Provides a fresh and natural layer of colou...,2023-11-25T18:34:41+02:00,Pupa,Makeup,1680,2100.0,True,41678823882884,3,721050225A003,True,Pupa Wonder Me Blush - 3,1680,2100.0,8011607377299,https://cdn.shopify.com/s/files/1/0377/3258/15...

In [3]:
df['product_url'] = 'https://moustaphalabban.com/products/' + df['handle']
display(df.head())

,product_id,title,handle,description,created_at,vendor,type,price,compare_at_price,available,variant_id,variant_title,variant_sku,variant_available,variant_name,variant_price,variant_compare_at_price,variant_barcode,variant_image,product_url
0,10162396299396,Pupa Wonder Me Shiny Bronzer,pupa-wonder-me-shiny-bronzer,"<p>Recreates a natural tan effect, warming and...",2025-11-08T00:55:06+02:00,Pupa,Makeup,2320,2900.0,True,51266399502468,001 Light Neutral,721050244A001,True,Pupa Wonder Me Shiny Bronzer - 001 Light Neutral,2320,2900.0,8011607401284,https://cdn.shopify.com/s/files/1/0377/3258/15...,https://moustaphalabban.com/products/pupa-wond...
1,10162396299396,Pupa Wonder Me Shiny Bronzer,pupa-wonder-me-shiny-bronzer,"<p>Recreates a natural tan effect, warming and...",2025-11-08T00:55:06+02:00,Pupa,Makeup,2320,2900.0,True,51266399535236,002 Medium Warm,721050244A002,True,Pupa Wonder Me Shiny Bronzer - 002 Medium Warm,2320,2900.0,8011607401291,https://cdn.shopify.com/s/files/1/0377/3258/15...,https://moustaphalabban.com/products/pupa-wond...
2,10162396299396,Pupa Wonder Me Shiny Bronzer,pupa-wonder-me-shiny-bronzer,"<p>Recreates a natural tan effect, warming and...",2025-11-08T00:55:06+02:00,Pupa,Makeup,2320,2900.0,True,51266399568004,003 Medium Neutral,721050244A003,True,Pupa Wonder Me Shiny Bronzer - 003 Medium Neutral,2320,2900.0,8011607401307,https://cdn.shopify.com/s/files/1/0377/3258/15...,https://moustaphalabban.com/products/pupa-wond...
3,10162396299396,Pupa Wonder Me Shiny Bronzer,pupa-wonder-me-shiny-bronzer,"<p>Recreates a natural tan effect, warming and...",2025-11-08T00:55:06+02:00,Pupa,Makeup,2320,2900.0,True,51266399600772,004 Dark Warm,721050244A004,True,Pupa Wonder Me Shiny Bronzer - 004 Dark Warm,2320,2900.0,8011607401314,https://cdn.shopify.com/s/files/1/0377/3258/15...,https://moustaphalabban.com/products/pupa-wond...
4,7203500097668,Pupa Wonder Me Blush,pupa-wonder-me-blush,<p>Provides a fresh and natural layer of colou...,2023-11-25T18:34:41+02:00,Pupa,Makeup,1680,2100.0,True,41678823882884,3,721050225A003,True,Pupa Wonder Me Blush - 3,1680,2100.0,8011607377299,https://cdn.shopify.com/s/files/1/0377/3258/15...,https://moustaphalabban.com/products/pupa-wond...

In [4]:
df['public_variant_price'] = df['variant_price'].apply(lambda x: f'${x/100:.2f}')
display(df.head())

,product_id,title,handle,description,created_at,vendor,type,price,compare_at_price,available,...,variant_title,variant_sku,variant_available,variant_name,variant_price,variant_compare_at_price,variant_barcode,variant_image,product_url,public_variant_price
0,10162396299396,Pupa Wonder Me Shiny Bronzer,pupa-wonder-me-shiny-bronzer,"<p>Recreates a natural tan effect, warming and...",2025-11-08T00:55:06+02:00,Pupa,Makeup,2320,2900.0,True,...,001 Light Neutral,721050244A001,True,Pupa Wonder Me Shiny Bronzer - 001 Light Neutral,2320,2900.0,8011607401284,https://cdn.shopify.com/s/files/1/0377/3258/15...,https://moustaphalabban.com/products/pupa-wond...,$23.20
1,10162396299396,Pupa Wonder Me Shiny Bronzer,pupa-wonder-me-shiny-bronzer,"<p>Recreates a natural tan effect, warming and...",2025-11-08T00:55:06+02:00,Pupa,Makeup,2320,2900.0,True,...,002 Medium Warm,721050244A002,True,Pupa Wonder Me Shiny Bronzer - 002 Medium Warm,2320,2900.0,8011607401291,https://cdn.shopify.com/s/files/1/0377/3258/15...,https://moustaphalabban.com/products/pupa-wond...,$23.20
2,10162396299396,Pupa Wonder Me Shiny Bronzer,pupa-wonder-me-shiny-bronzer,"<p>Recreates a natural tan effect, warming and...",2025-11-08T00:55:06+02:00,Pupa,Makeup,2320,2900.0,True,...,003 Medium Neutral,721050244A003,True,Pupa Wonder Me Shiny Bronzer - 003 Medium Neutral,2320,2900.0,8011607401307,https://cdn.shopify.com/s/files/1/0377/3258/15...,https://moustaphalabban.com/products/pupa-wond...,$23.20
3,10162396299396,Pupa Wonder Me Shiny Bronzer,pupa-wonder-me-shiny-bronzer,"<p>Recreates a natural tan effect, warming and...",2025-11-08T00:55:06+02:00,Pupa,Makeup,2320,2900.0,True,...,004 Dark Warm,721050244A004,True,Pupa Wonder Me Shiny Bronzer - 004 Dark Warm,2320,2900.0,8011607401314,https://cdn.shopify.com/s/files/1/0377/3258/15...,https://moustaphalabban.com/products/pupa-wond...,$23.20
4,7203500097668,Pupa Wonder Me Blush,pupa-wonder-me-blush,<p>Provides a fresh and natural layer of colou...,2023-11-25T18:34:41+02:00,Pupa,Makeup,1680,2100.0,True,...,3,721050225A003,True,Pupa Wonder Me Blush - 3,1680,2100.0,8011607377299,https://cdn.shopify.com/s/files/1/0377/3258/15...,https://moustaphalabban.com/products/pupa-wond...,$16.80

In [5]:
df['public_variant_compare_at_price'] = df['variant_compare_at_price'].apply(lambda x: f'${x/100:.2f}')
display(df.head())

,product_id,title,handle,description,created_at,vendor,type,price,compare_at_price,available,...,variant_sku,variant_available,variant_name,variant_price,variant_compare_at_price,variant_barcode,variant_image,product_url,public_variant_price,public_variant_compare_at_price
0,10162396299396,Pupa Wonder Me Shiny Bronzer,pupa-wonder-me-shiny-bronzer,"<p>Recreates a natural tan effect, warming and...",2025-11-08T00:55:06+02:00,Pupa,Makeup,2320,2900.0,True,...,721050244A001,True,Pupa Wonder Me Shiny Bronzer - 001 Light Neutral,2320,2900.0,8011607401284,https://cdn.shopify.com/s/files/1/0377/3258/15...,https://moustaphalabban.com/products/pupa-wond...,$23.20,$29.00
1,10162396299396,Pupa Wonder Me Shiny Bronzer,pupa-wonder-me-shiny-bronzer,"<p>Recreates a natural tan effect, warming and...",2025-11-08T00:55:06+02:00,Pupa,Makeup,2320,2900.0,True,...,721050244A002,True,Pupa Wonder Me Shiny Bronzer - 002 Medium Warm,2320,2900.0,8011607401291,https://cdn.shopify.com/s/files/1/0377/3258/15...,https://moustaphalabban.com/products/pupa-wond...,$23.20,$29.00
2,10162396299396,Pupa Wonder Me Shiny Bronzer,pupa-wonder-me-shiny-bronzer,"<p>Recreates a natural tan effect, warming and...",2025-11-08T00:55:06+02:00,Pupa,Makeup,2320,2900.0,True,...,721050244A003,True,Pupa Wonder Me Shiny Bronzer - 003 Medium Neutral,2320,2900.0,8011607401307,https://cdn.shopify.com/s/files/1/0377/3258/15...,https://moustaphalabban.com/products/pupa-wond...,$23.20,$29.00
3,10162396299396,Pupa Wonder Me Shiny Bronzer,pupa-wonder-me-shiny-bronzer,"<p>Recreates a natural tan effect, warming and...",2025-11-08T00:55:06+02:00,Pupa,Makeup,2320,2900.0,True,...,721050244A004,True,Pupa Wonder Me Shiny Bronzer - 004 Dark Warm,2320,2900.0,8011607401314,https://cdn.shopify.com/s/files/1/0377/3258/15...,https://moustaphalabban.com/products/pupa-wond...,$23.20,$29.00
4,7203500097668,Pupa Wonder Me Blush,pupa-wonder-me-blush,<p>Provides a fresh and natural layer of colou...,2023-11-25T18:34:41+02:00,Pupa,Makeup,1680,2100.0,True,...,721050225A003,True,Pupa Wonder Me Blush - 3,1680,2100.0,8011607377299,https://cdn.shopify.com/s/files/1/0377/3258/15...,https://moustaphalabban.com/products/pupa-wond...,$16.80,$21.00

In [6]:
output_filename = 'moustaphalabban_products_processed.csv'
df.to_csv(output_filename, index=False)
print(f"DataFrame successfully saved to {output_filename}")

DataFrame successfully saved to moustaphalabban_products_processed.csv

In [7]:
from google.colab import files
files.download(output_filename)