In [ ]:
import requests
import json
import time

URL = "https://api.miaburton.com/graphql"

HEADERS = {
    "accept": "*/*",
    "content-type": "application/json",
    "country": "US",
    "currency": "USD",
    "language": "en",
    "origin": "https://miaburton.com",
    "referer": "https://miaburton.com/en/eyeglasses/women/2",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    # ⚠️ must be fresh
    "miaburton-req-seed": "1769389259086",
    "miaburton-req-signature": "8c3e06a3af7b357a6c99f63b0eacf1038daf8d21efbe481a0d48bea053b3e545",
    "miaburton-req-timestamp": "1769389259086",
}

QUERY = """
query ProductsAndSiblings($input: ProductFilterInput!) {
  productsAndSiblings(input: $input) {
    items {
      sku
      brand {
        name
        slug
        uuid
      }
      category {
        name
      }
      siblings {
        name
        price
        discountPrice
        polarized
        blueFilter
        photochromic
        uuid
        slug
        sku
        modelName
        modelCode
        modelAlias
        colorCode
        colorAlias
        shape
        canonical
        bestSeller
        outOfStock
        vmEnabled
        vmAuglioEnabled
        identifier3d
        clipOn
        smart
        fastShipping
        patterns
        frameColors
        images {
          resolutions
          path
          name
        }
        translations {
          path
          language {
            label
          }
        }
      }
    }
    pageInfo {
      count
      pages
      curr
      prev
      next
    }
  }
}
"""

def fetch_all_products():
    all_items = []
    page = 1

    while True:
        payload = {
            "operationName": "ProductsAndSiblings",
            "variables": {
                "input": {
                    "filter": {
                        "category": {"eq": "sunglasses"}
                    },
                    "perPage": 100,
                    "page": page,
                    "sort": {
                        "by": "publishingDate",
                        "direction": "DESC"
                    }
                }
            },
            "query": QUERY
        }

        resp = requests.post(URL, headers=HEADERS, json=payload)
        resp.raise_for_status()
        data = resp.json()

        # 🚨 GraphQL error handling
        if "errors" in data:
            print("GraphQL errors:")
            print(json.dumps(data["errors"], indent=2))
            break

        result = data.get("data", {}).get("productsAndSiblings")

        if result is None:
            print("productsAndSiblings is null. Full response:")
            print(json.dumps(data, indent=2))
            break

        items = result["items"]
        page_info = result["pageInfo"]

        print(f"Page {page}/{page_info['pages']} → {len(items)} items")
        # print(items)
        all_items.extend(items)

        if not page_info["next"]:
            break

        page += 1
        time.sleep(0.4)

    return all_items


if __name__ == "__main__":
    products = fetch_all_products()
    print(f"\nFetched total: {len(products)} products")
    with open("sunglasses.json", "w", encoding="utf-8") as f:
      json.dump(products, f, ensure_ascii=False, indent=2)

    print(f"\n✅ Done. Total products fetched: {len(products)}")

GraphQL errors:
[
  {
    "message": "Cannot read properties of undefined (reading 'raw')",
    "locations": [
      {
        "line": 3,
        "column": 3
      }
    ],
    "path": [
      "productsAndSiblings"
    ],
    "extensions": {
      "code": "INTERNAL_SERVER_ERROR",
      "stacktrace": [
        "TypeError: Cannot read properties of undefined (reading 'raw')",
        "    at FastifyAdapter.getRequestUrl (/var/www/api.miaburton.com/releases/20260121131931/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:262:51)",
        "    at AllExceptionsFilter.catch (/var/www/api.miaburton.com/releases/20260121131931/dist/all-exceptions.filter.js:37:31)",
        "    at ExternalExceptionsHandler.invokeCustomFilters (/var/www/api.miaburton.com/releases/20260121131931/node_modules/@nestjs/core/exceptions/external-exceptions-handler.js:34:32)",
        "    at ExternalExceptionsHandler.next (/var/www/api.miaburton.com/releases/20260121131931/node_modules/@nestjs/core/exceptions/external-exceptions-handler.js:13:29)",
        "    at Object.productsAndSiblings (/var/www/api.miaburton.com/releases/20260121131931/node_modules/@nestjs/core/helpers/external-proxy.js:14:42)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"
      ]
    }
  }
]

Fetched total: 0 products

✅ Done. Total products fetched: 0

In [ ]:
import json

json_data = {"operationName":"ProductsAndSiblings","variables":{"input":{"filter":{"category":{"eq":"eyeglasses"},"gender":{"in":["F","U"]}},"perPage":24,"page":5,"sort":{"by":"publishingDate","direction":"DESC"}}},"query":"query ProductsAndSiblings($input: ProductFilterInput!) {\n  productsAndSiblings(input: $input) {\n    items {\n      sku\n      brand {\n        name\n        slug\n        uuid\n      }\n      category {\n        name\n      }\n      siblings {\n        name\n        price\n        discountPrice\n        polarized\n        blueFilter\n        photochromic\n        uuid\n        slug\n        sku\n        modelName\n        modelCode\n        modelAlias\n        colorCode\n        colorAlias\n        shape\n        canonical\n        bestSeller\n        outOfStock\n        vmEnabled\n        vmAuglioEnabled\n        identifier3d\n        clipOn\n        smart\n        fastShipping\n        patterns\n        frameColors\n        images {\n          resolutions\n          path\n          name\n        }\n        translations {\n          path\n          language {\n            label\n          }\n        }\n      }\n    }\n    pageInfo {\n      count\n      pages\n      curr\n      prev\n      next\n    }\n  }\n}"}

graphql_query = json_data.get("query")

print(graphql_query)

query ProductsAndSiblings($input: ProductFilterInput!) {
  productsAndSiblings(input: $input) {
    items {
      sku
      brand {
        name
        slug
        uuid
      }
      category {
        name
      }
      siblings {
        name
        price
        discountPrice
        polarized
        blueFilter
        photochromic
        uuid
        slug
        sku
        modelName
        modelCode
        modelAlias
        colorCode
        colorAlias
        shape
        canonical
        bestSeller
        outOfStock
        vmEnabled
        vmAuglioEnabled
        identifier3d
        clipOn
        smart
        fastShipping
        patterns
        frameColors
        images {
          resolutions
          path
          name
        }
        translations {
          path
          language {
            label
          }
        }
      }
    }
    pageInfo {
      count
      pages
      curr
      prev
      next
    }
  }
}

In [ ]:
with open("products.json", "w", encoding="utf-8") as f:
    json.dump(products, f, ensure_ascii=False, indent=2)

print(f"\n✅ Done. Total products fetched: {len(products)}")

✅ Done. Total products fetched: 2747

In [ ]:
products[0]

{'sku': '00_538228707',
 'brand': {'name': 'Balenciaga',
  'slug': 'balenciaga',
  'uuid': '77fdab9c-59ac-45af-b98b-ae9f9ab725c6'},
 'category': {'name': 'eyeglasses'},
 'siblings': [{'name': 'BB0490O',
   'price': 7054919,
   'discountPrice': 7054919,
   'polarized': False,
   'blueFilter': False,
   'photochromic': False,
   'uuid': 'f386a00e-7435-44a5-b30f-4039aafd004d',
   'slug': 'balenciaga-bb0490o-002',
   'sku': '00_538228707',
   'modelName': None,
   'modelCode': 'BB0490O',
   'modelAlias': '',
   'colorCode': '002',
   'colorAlias': 'Black',
   'shape': 'rectangle',
   'canonical': 'bb0490o-004',
   'bestSeller': False,
   'outOfStock': False,
   'vmEnabled': False,
   'vmAuglioEnabled': False,
   'identifier3d': None,
   'clipOn': False,
   'smart': False,
   'fastShipping': True,
   'patterns': [],
   'frameColors': ['black'],
   'images': [{'resolutions': ['1600x1600',
      '784x784',
      '540x540',
      '376x376',
      '255x255',
      '100x100'],
     'path': '2026/balenciaga-bb0490o-002.jpg',
     'name': 'balenciaga-bb0490o-002'},
    {'resolutions': ['1600x1600',
      '784x784',
      '540x540',
      '376x376',
      '255x255',
      '100x100'],
     'path': '2026/balenciaga-bb0490o-002-img1.jpg',
     'name': 'balenciaga-bb0490o-002 (1)'}],
   'translations': [{'path': 'eyeglasses/balenciaga/bb0490o-002',
     'language': {'label': 'en'}}]},
  {'name': 'BB0490O',
   'price': 7054919,
   'discountPrice': 7054919,
   'polarized': False,
   'blueFilter': False,
   'photochromic': False,
   'uuid': '605d3aac-9aac-48dd-8fb9-be9d58b0ae2a',
   'slug': 'balenciaga-bb0490o-004',
   'sku': '00_538228708',
   'modelName': None,
   'modelCode': 'BB0490O',
   'modelAlias': '',
   'colorCode': '004',
   'colorAlias': 'Gold',
   'shape': 'rectangle',
   'canonical': None,
   'bestSeller': False,
   'outOfStock': False,
   'vmEnabled': False,
   'vmAuglioEnabled': False,
   'identifier3d': None,
   'clipOn': False,
   'smart': False,
   'fastShipping': True,
   'patterns': [],
   'frameColors': ['gold'],
   'images': [{'resolutions': ['1600x1600',
      '784x784',
      '540x540',
      '376x376',
      '255x255',
      '100x100'],
     'path': '2026/balenciaga-bb0490o-004.jpg',
     'name': 'balenciaga-bb0490o-004'},
    {'resolutions': ['1600x1600',
      '784x784',
      '540x540',
      '376x376',
      '255x255',
      '100x100'],
     'path': '2026/balenciaga-bb0490o-004-img1.jpg',
     'name': 'balenciaga-bb0490o-004 (1)'}],
   'translations': [{'path': 'eyeglasses/balenciaga/bb0490o-004',
     'language': {'label': 'en'}}]}]}

In [ ]:
from playwright.sync_api import sync_playwright
import json

def run():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
        )
        page = context.new_page()

        # Variable to store our target headers
        captured_headers = {}

        # Define the listener function
        def handle_request(request):
            if "api.miaburton.com/graphql" in request.url and request.method == "POST":
                # We only want the headers if they contain the specific signature keys
                headers = request.headers
                if "miaburton-req-signature" in headers:
                    nonlocal captured_headers
                    captured_headers = headers
                    print("Found GraphQL Headers!")

        # Attach the listener
        page.on("request", handle_request)

        print("Navigating to page 1...")
        page.goto("https://miaburton.com/en/eyeglasses", wait_until="domcontentloaded")

        # Wait for the next button to be visible
        next_button_selector = 'a[data-cy="pagination-next"]'
        page.wait_for_selector(next_button_selector)

        print("Clicking 'Next Page' to trigger GraphQL request...")

        # We use a context manager to wait for the specific network response
        # triggered by the click
        with page.expect_response("**/graphql") as response_info:
            page.click(next_button_selector)

        # Ensure we captured something
        if captured_headers:
            print("\n--- Captured GraphQL Headers ---")
            print(json.dumps(dict(captured_headers), indent=4))

            # Save to file
            with open("graphql_headers.json", "w") as f:
                json.dump(dict(captured_headers), f, indent=4)
        else:
            print("Failed to capture specific GraphQL headers.")

        # Also keep your cookies as requested previously
        cookies = context.cookies()
        with open("cookies2.json", "w") as f:
            json.dump(cookies, f, indent=4)

        browser.close()

if __name__ == "__main__":
    run()

In [1]:
import pandas as pd

df_products1 = pd.read_csv('/content/products1.csv')
print("First 5 rows of products1.csv:")
display(df_products1.head())

First 5 rows of products1.csv:

,product_id,product_title,vendor,product_type,handle/url,description,variant_id,variant_title,sku,price,compare_at_price,color,size,available,barcode,image_url
0,00_538222048,Dolce & Gabbana DG3433,Dolce & Gabbana,eyeglasses,https://miaburton.com/en/eyeglasses/dolce-and-...,NaN,e689f95c-0a02-4c01-916d-7876591e3038,Pearl Havana Purple,00_538222048,253,362,Pearl Havana Purple,NaN,True,NaN,https://cdn.miaburton.com/2025/dolce-and-gabba...
1,00_538222048,Dolce & Gabbana Dolce & Gabbana DG3433 502 Havana,Dolce & Gabbana,eyeglasses,https://miaburton.com/en/eyeglasses/dolce-and-...,NaN,88c5da42-2122-46b7-8ab6-32490206d948,Havana,00_538222050,252,360,Havana,NaN,True,NaN,https://cdn.miaburton.com/2025/dolce-and-gabba...
2,00_538222048,Dolce & Gabbana Dolce & Gabbana DG3433 501 Black,Dolce & Gabbana,eyeglasses,https://miaburton.com/en/eyeglasses/dolce-and-...,NaN,abfa0e8d-2116-472b-b2ec-f77a8d50b073,Black,00_538222049,252,360,Black,NaN,True,NaN,https://cdn.miaburton.com/2025/dolce-and-gabba...
3,00_538231699,Dolce & Gabbana DG3440 Eyeglasses,Dolce & Gabbana,eyeglasses,https://miaburton.com/en/eyeglasses/dolce-and-...,NaN,56bbd97f-616f-4be8-ab85-d94cc3e375a7,Black,00_538231699,309,309,Black,NaN,True,NaN,https://cdn.miaburton.com/2026/dolce-and-gabba...
4,00_538231699,Dolce & Gabbana DG3440 Eyeglasses,Dolce & Gabbana,eyeglasses,https://miaburton.com/en/eyeglasses/dolce-and-...,NaN,8836fd06-9055-4439-af35-96baa3094576,Nude Transparent,00_538231701,305,305,Nude Transparent,NaN,True,NaN,https://cdn.miaburton.com/2026/dolce-and-gabba...

In [2]:
import pandas as pd

df_products2 = pd.read_csv('/content/products2.csv')
print("\nFirst 5 rows of products2.csv:")
display(df_products2.head())

First 5 rows of products2.csv:

,product_name,product_url,brand,color,sku,description,image_url,barcode,ean,available
0,Even Realities G2-A Eyeglasses,https://miaburton.com/en/eyeglasses/even-reali...,Even Realities,brown,00_538233845,<p>Introducing the Even Realities G2-A Brown e...,https://cdn.miaburton.com/2026/even-realities-...,9.053810e+12,NaN,True
1,Even Realities G2-A Eyeglasses,https://miaburton.com/en/eyeglasses/even-reali...,Even Realities,green,00_538233708,<p>Introducing the Even Realities G2-A GREEN e...,https://cdn.miaburton.com/2026/even-realities-...,9.053810e+12,NaN,True
2,Even Realities G2-A,https://miaburton.com/en/eyeglasses/even-reali...,Even Realities,grey,00_538230342,<p><strong>Important: This product is not elig...,https://cdn.miaburton.com/2026/even-realities-...,9.053810e+12,NaN,True
3,Even Realities G2-B Eyeglasses,https://miaburton.com/en/eyeglasses/even-reali...,Even Realities,brown,00_538231154,<p>Introducing the Even Realities G2-B Brown e...,https://cdn.miaburton.com/2026/even-realities-...,9.053810e+12,NaN,True
4,Even Realities G2-B Eyeglasses,https://miaburton.com/en/eyeglasses/even-reali...,Even Realities,green,00_538233709,<p>The Even Realities G2-B GREEN eyeglasses fe...,https://cdn.miaburton.com/2026/even-realities-...,9.053810e+12,NaN,True

In [4]:
import pandas as pd

FILE_1 = "products1.csv"
FILE_2 = "products2.csv"
OUTPUT_FILE = "enriched_output.csv"

# ================================
# 📥 LOAD
# ================================
df1 = pd.read_csv(FILE_1)
df2 = pd.read_csv(FILE_2)

# ================================
# 🧼 CLEAN SKU
# ================================
df1["sku"] = df1["sku"].astype(str).str.strip()
df2["sku"] = df2["sku"].astype(str).str.strip()

# ================================
# 🧠 CHECK AVAILABLE COLUMNS
# ================================
columns_to_merge = ["sku"]

optional_cols = ["description", "color", "barcode", "ean"]

for col in optional_cols:
    if col in df2.columns:
        columns_to_merge.append(col)
    else:
        print(f"⚠️ Column '{col}' not found in second CSV")

# ================================
# 🔗 MERGE
# ================================
merged = df1.merge(
    df2[columns_to_merge],
    on="sku",
    how="left",
    suffixes=("", "_new")
)

# ================================
# 🧠 ENRICH LOGIC (SAFE)
# ================================

def safe_update(col):
    new_col = col + "_new"
    if new_col in merged.columns:
        merged[col] = merged[col].combine_first(merged[new_col])

# apply updates safely
safe_update("description")
safe_update("barcode")

# color (only fill missing)
if "color_new" in merged.columns:
    merged["color"] = merged["color"].combine_first(merged["color_new"])

# ean (create if not exists)
if "ean_new" in merged.columns:
    if "ean" not in merged.columns:
        merged["ean"] = merged["ean_new"]
    else:
        merged["ean"] = merged["ean"].combine_first(merged["ean_new"])

# ================================
# 🧹 CLEAN TEMP COLUMNS
# ================================
merged.drop(columns=[c for c in merged.columns if c.endswith("_new")], inplace=True)

# ================================
# 💾 SAVE
# ================================
merged.to_csv(OUTPUT_FILE, index=False, encoding="utf-8-sig")

print(f"✅ Done! Saved: {OUTPUT_FILE}")

✅ Done! Saved: enriched_output.csv

In [5]:
merged

,product_id,product_title,vendor,product_type,handle/url,description,variant_id,variant_title,sku,price,compare_at_price,color,size,available,barcode,image_url,ean
0,00_538222048,Dolce & Gabbana DG3433,Dolce & Gabbana,eyeglasses,https://miaburton.com/en/eyeglasses/dolce-and-...,Introducing the Dolce & Gabbana DG3433 3464 ey...,e689f95c-0a02-4c01-916d-7876591e3038,Pearl Havana Purple,00_538222048,253,362,Pearl Havana Purple,NaN,True,9.053810e+12,https://cdn.miaburton.com/2025/dolce-and-gabba...,8.056260e+12
1,00_538222048,Dolce & Gabbana Dolce & Gabbana DG3433 502 Havana,Dolce & Gabbana,eyeglasses,https://miaburton.com/en/eyeglasses/dolce-and-...,Designer: DOLCE & GABBANA | Style ID: DG3433 |...,88c5da42-2122-46b7-8ab6-32490206d948,Havana,00_538222050,252,360,Havana,NaN,True,9.053810e+12,https://cdn.miaburton.com/2025/dolce-and-gabba...,8.056260e+12
2,00_538222048,Dolce & Gabbana Dolce & Gabbana DG3433 501 Black,Dolce & Gabbana,eyeglasses,https://miaburton.com/en/eyeglasses/dolce-and-...,Designer: DOLCE & GABBANA | Style ID: DG3433 |...,abfa0e8d-2116-472b-b2ec-f77a8d50b073,Black,00_538222049,252,360,Black,NaN,True,9.053810e+12,https://cdn.miaburton.com/2025/dolce-and-gabba...,8.056260e+12
3,00_538231699,Dolce & Gabbana DG3440 Eyeglasses,Dolce & Gabbana,eyeglasses,https://miaburton.com/en/eyeglasses/dolce-and-...,Discover the allure of Dolce & Gabbana's DG344...,56bbd97f-616f-4be8-ab85-d94cc3e375a7,Black,00_538231699,309,309,Black,NaN,True,9.053810e+12,https://cdn.miaburton.com/2026/dolce-and-gabba...,8.056260e+12
4,00_538231699,Dolce & Gabbana DG3440 Eyeglasses,Dolce & Gabbana,eyeglasses,https://miaburton.com/en/eyeglasses/dolce-and-...,Elevate your eyewear collection with the Dolce...,8836fd06-9055-4439-af35-96baa3094576,Nude Transparent,00_538231701,305,305,Nude Transparent,NaN,True,9.053810e+12,https://cdn.miaburton.com/2026/dolce-and-gabba...,8.056260e+12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21593,00_538226928,Ray-Ban RW4013,Ray-Ban,sunglasses,https://miaburton.com/en/sunglasses/ray-ban/rw...,<p>The Ray-Ban Wayfarer Meta smart sunglasses ...,9f5a9316-ac54-46d2-b77c-0429a200952c,Black,00_538226928,379,379,Black,NaN,False,9.053810e+12,https://cdn.miaburton.com/2025/ray-ban-rw4013-...,8.056260e+12
21594,00_538224547,Ray-Ban SKYLER,Ray-Ban,sunglasses,https://miaburton.com/en/sunglasses/ray-ban/sk...,<p>Embrace a jet-set lifestyle with the Ray-Ba...,89b9a0fd-bfab-415a-96bf-a17c0b5087cb,Grey,00_538217456,349,349,Grey,NaN,False,9.053810e+12,https://cdn.miaburton.com/2025/ray-ban-skyler-...,8.056260e+12
21595,00_538224547,Ray-Ban SKYLER,Ray-Ban,sunglasses,https://miaburton.com/en/sunglasses/ray-ban/sk...,<p>Embrace a jet-set lifestyle with the Ray-Ba...,89b9a0fd-bfab-415a-96bf-a17c0b5087cb,Grey,00_538217456,349,349,Grey,NaN,False,9.053810e+12,https://cdn.miaburton.com/2025/ray-ban-skyler-...,8.056260e+12
21596,00_538224547,Ray-Ban SKYLER,Ray-Ban,sunglasses,https://miaburton.com/en/sunglasses/ray-ban/sk...,<p>Command the future of style. The Ray-Ban Me...,6197d340-bd47-4798-9d6e-350b3fcaf7d6,Black,00_538224547,299,299,Black,NaN,False,9.053810e+12,https://cdn.miaburton.com/2025/ray-ban-skyler-...,8.056260e+12
21597,00_538224547,Ray-Ban SKYLER,Ray-Ban,sunglasses,https://miaburton.com/en/sunglasses/ray-ban/sk...,<p>Command the future of style. The Ray-Ban Me...,6197d340-bd47-4798-9d6e-350b3fcaf7d6,Black,00_538224547,299,299,Black,NaN,False,9.053810e+12,https://cdn.miaburton.com/2025/ray-ban-skyler-...,8.056260e+12