In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Upwork/hoofar/rugs_metadata.csv')
display(df.head())

,public_url,name,barcode,description,condition_details,width,height,depth,sale_starts_at,sale_ends_at,minimum_bid_amount,high_bid_amount,main_image,images,sale_id,type_name,time_status,manufacturer,product_url,type
0,https://www.ebth.com/items/14433729-4-11-x-7-3...,"4'11 x 7'3 Hand-Knotted Persian Hamadan ""Mosul...",ITMGP93717,This authentic Iranian hand-knotted rug origin...,"- color shifts, abrash and dye bleed; snags, p...",87.00,0.25,59.0,2026-04-02 06:00:00+00:00,2026-04-09 01:31:20+00:00,300,275,https://imgix-prod.ebth.com/2026/03/19/14/06/4...,['https://imgix-prod.ebth.com/2026/03/19/14/06...,88018,standard,extended,handmade,NaN,Hamadan
1,https://www.ebth.com/items/14429164-antique-9-...,Antique 9' x 11'8 Hand-Knotted Heriz Rug,ITMGS84647,NaN,"- significant pile wear throughout, revealing ...",107.50,0.25,140.0,2026-03-30 06:00:00+00:00,2026-04-06 00:04:40+00:00,3070,3020,https://imgix-prod.ebth.com/2026/03/12/19/35/5...,['https://imgix-prod.ebth.com/2026/03/12/19/35...,88774,standard,ended,handmade,NaN,Heriz
2,https://www.ebth.com/items/14429029-4-2-x-7-5-...,4'2 x 7'5 Hand-Knotted Persian Tabriz Area Rug,ITMGS84649,This authentic Persian Tabriz rug exemplifies ...,"- discolorations and spot stains, especially t...",49.50,0.25,89.0,2026-03-30 06:00:00+00:00,2026-04-05 23:54:22+00:00,632,607,https://imgix-prod.ebth.com/2026/03/12/19/16/5...,['https://imgix-prod.ebth.com/2026/03/12/19/16...,88774,standard,ended,handmade,NaN,Tabriz
3,https://www.ebth.com/items/14429053-antique-10...,Antique 10'1 x 18'4 Hand-Knotted Persian Sarou...,ITMGS84648,This authentic Persian Sarouk carpet is a mast...,- traffic wear with crushed pile; low pile wit...,121.00,0.25,219.0,2026-03-30 06:00:00+00:00,2026-04-05 23:45:57+00:00,752,727,https://imgix-prod.ebth.com/2026/03/12/19/30/0...,['https://imgix-prod.ebth.com/2026/03/12/19/30...,88774,standard,ended,handmade,NaN,Sarouk
4,https://www.ebth.com/items/14436297-8-7-x-11-7...,8'7 x 11'7 Hand-Knotted Persian Heriz Area Rug,ITMGR15514,Authentic hand-knotted Persian Heriz rug. Feat...,- creased from storage; crushed pile; dye blee...,102.75,0.25,139.0,2026-03-29 06:00:00+00:00,2026-04-05 00:21:11+00:00,789,764,https://imgix-prod.ebth.com/2026/03/20/14/03/5...,['https://imgix-prod.ebth.com/2026/03/20/14/03...,88395,standard,ended,handmade,NaN,Heriz

In [3]:
(df.isnull().sum() / len(df)) * 100

public_url              0.000000
name                    0.000000
barcode                 0.000000
description            80.897042
condition_details       4.552439
width                   0.000000
height                  0.000000
depth                   0.000000
sale_starts_at          0.000000
sale_ends_at            0.000000
minimum_bid_amount      0.000000
high_bid_amount         0.000000
main_image              0.000000
images                  0.000000
sale_id                 0.000000
type_name               0.000000
time_status             0.000000
manufacturer            0.000000
product_url           100.000000
type                    0.000000
dtype: float64

In [4]:
df.isnull().sum()[df.isnull().sum() > 0]

description           8423
condition_details      474
product_url          10412
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10412 entries, 0 to 10411
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   public_url          10412 non-null  object
 1   name                10412 non-null  object
 2   barcode             10412 non-null  object
 3   description         1989 non-null   object
 4   condition_details   9938 non-null   object
 5   width               10412 non-null  float64
 6   height              10412 non-null  float64
 7   depth               10412 non-null  float64
 8   sale_starts_at      10412 non-null  object
 9   sale_ends_at        10412 non-null  object
 10  minimum_bid_amount  10412 non-null  int64
 11  high_bid_amount     10412 non-null  int64
 12  main_image          10412 non-null  object
 13  images              10412 non-null  object
 14  sale_id             10412 non-null  int64
 15  type_name           10412 non-null  object
 16  time_status         10412 non-null  object
 17  manufacturer        10412 non-null  object
 18  product_url         0 non-null      float64
 19  type                10412 non-null  object
dtypes: float64(4), int64(3), object(13)
memory usage: 1.6+ MB

In [7]:
# Drop useless column
df = df.drop(columns=['product_url'])

# Convert datetime columns
df['sale_starts_at'] = pd.to_datetime(df['sale_starts_at'])
df['sale_ends_at'] = pd.to_datetime(df['sale_ends_at'])

df.head()

,public_url,name,barcode,description,condition_details,width,height,depth,sale_starts_at,sale_ends_at,minimum_bid_amount,high_bid_amount,main_image,images,sale_id,type_name,time_status,manufacturer,type
0,https://www.ebth.com/items/14433729-4-11-x-7-3...,"4'11 x 7'3 Hand-Knotted Persian Hamadan ""Mosul...",ITMGP93717,This authentic Iranian hand-knotted rug origin...,"- color shifts, abrash and dye bleed; snags, p...",87.00,0.25,59.0,2026-04-02 06:00:00+00:00,2026-04-09 01:31:20+00:00,300,275,https://imgix-prod.ebth.com/2026/03/19/14/06/4...,['https://imgix-prod.ebth.com/2026/03/19/14/06...,88018,standard,extended,handmade,Hamadan
1,https://www.ebth.com/items/14429164-antique-9-...,Antique 9' x 11'8 Hand-Knotted Heriz Rug,ITMGS84647,NaN,"- significant pile wear throughout, revealing ...",107.50,0.25,140.0,2026-03-30 06:00:00+00:00,2026-04-06 00:04:40+00:00,3070,3020,https://imgix-prod.ebth.com/2026/03/12/19/35/5...,['https://imgix-prod.ebth.com/2026/03/12/19/35...,88774,standard,ended,handmade,Heriz
2,https://www.ebth.com/items/14429029-4-2-x-7-5-...,4'2 x 7'5 Hand-Knotted Persian Tabriz Area Rug,ITMGS84649,This authentic Persian Tabriz rug exemplifies ...,"- discolorations and spot stains, especially t...",49.50,0.25,89.0,2026-03-30 06:00:00+00:00,2026-04-05 23:54:22+00:00,632,607,https://imgix-prod.ebth.com/2026/03/12/19/16/5...,['https://imgix-prod.ebth.com/2026/03/12/19/16...,88774,standard,ended,handmade,Tabriz
3,https://www.ebth.com/items/14429053-antique-10...,Antique 10'1 x 18'4 Hand-Knotted Persian Sarou...,ITMGS84648,This authentic Persian Sarouk carpet is a mast...,- traffic wear with crushed pile; low pile wit...,121.00,0.25,219.0,2026-03-30 06:00:00+00:00,2026-04-05 23:45:57+00:00,752,727,https://imgix-prod.ebth.com/2026/03/12/19/30/0...,['https://imgix-prod.ebth.com/2026/03/12/19/30...,88774,standard,ended,handmade,Sarouk
4,https://www.ebth.com/items/14436297-8-7-x-11-7...,8'7 x 11'7 Hand-Knotted Persian Heriz Area Rug,ITMGR15514,Authentic hand-knotted Persian Heriz rug. Feat...,- creased from storage; crushed pile; dye blee...,102.75,0.25,139.0,2026-03-29 06:00:00+00:00,2026-04-05 00:21:11+00:00,789,764,https://imgix-prod.ebth.com/2026/03/20/14/03/5...,['https://imgix-prod.ebth.com/2026/03/20/14/03...,88395,standard,ended,handmade,Heriz

In [8]:
df['width_depth'] = df['width'] * df['depth']
df['width_height'] = df['width'] * df['height']
df['duration'] = (df['sale_ends_at'] - df['sale_starts_at']).dt.total_seconds()

In [9]:
df.head()

,public_url,name,barcode,description,condition_details,width,height,depth,sale_starts_at,sale_ends_at,...,main_image,images,sale_id,type_name,time_status,manufacturer,type,width_depth,width_height,duration
0,https://www.ebth.com/items/14433729-4-11-x-7-3...,"4'11 x 7'3 Hand-Knotted Persian Hamadan ""Mosul...",ITMGP93717,This authentic Iranian hand-knotted rug origin...,"- color shifts, abrash and dye bleed; snags, p...",87.00,0.25,59.0,2026-04-02 06:00:00+00:00,2026-04-09 01:31:20+00:00,...,https://imgix-prod.ebth.com/2026/03/19/14/06/4...,['https://imgix-prod.ebth.com/2026/03/19/14/06...,88018,standard,extended,handmade,Hamadan,5133.00,21.7500,588680.0
1,https://www.ebth.com/items/14429164-antique-9-...,Antique 9' x 11'8 Hand-Knotted Heriz Rug,ITMGS84647,NaN,"- significant pile wear throughout, revealing ...",107.50,0.25,140.0,2026-03-30 06:00:00+00:00,2026-04-06 00:04:40+00:00,...,https://imgix-prod.ebth.com/2026/03/12/19/35/5...,['https://imgix-prod.ebth.com/2026/03/12/19/35...,88774,standard,ended,handmade,Heriz,15050.00,26.8750,583480.0
2,https://www.ebth.com/items/14429029-4-2-x-7-5-...,4'2 x 7'5 Hand-Knotted Persian Tabriz Area Rug,ITMGS84649,This authentic Persian Tabriz rug exemplifies ...,"- discolorations and spot stains, especially t...",49.50,0.25,89.0,2026-03-30 06:00:00+00:00,2026-04-05 23:54:22+00:00,...,https://imgix-prod.ebth.com/2026/03/12/19/16/5...,['https://imgix-prod.ebth.com/2026/03/12/19/16...,88774,standard,ended,handmade,Tabriz,4405.50,12.3750,582862.0
3,https://www.ebth.com/items/14429053-antique-10...,Antique 10'1 x 18'4 Hand-Knotted Persian Sarou...,ITMGS84648,This authentic Persian Sarouk carpet is a mast...,- traffic wear with crushed pile; low pile wit...,121.00,0.25,219.0,2026-03-30 06:00:00+00:00,2026-04-05 23:45:57+00:00,...,https://imgix-prod.ebth.com/2026/03/12/19/30/0...,['https://imgix-prod.ebth.com/2026/03/12/19/30...,88774,standard,ended,handmade,Sarouk,26499.00,30.2500,582357.0
4,https://www.ebth.com/items/14436297-8-7-x-11-7...,8'7 x 11'7 Hand-Knotted Persian Heriz Area Rug,ITMGR15514,Authentic hand-knotted Persian Heriz rug. Feat...,- creased from storage; crushed pile; dye blee...,102.75,0.25,139.0,2026-03-29 06:00:00+00:00,2026-04-05 00:21:11+00:00,...,https://imgix-prod.ebth.com/2026/03/20/14/03/5...,['https://imgix-prod.ebth.com/2026/03/20/14/03...,88395,standard,ended,handmade,Heriz,14282.25,25.6875,584471.0

In [10]:
df['manufacturer_clean'] = df['manufacturer'].str.lower()

df['manufacturer_clean'].value_counts()

manufacturer_clean
handmade        10260
machine-made      152
Name: count, dtype: int64

In [11]:
df['type_clean'] = df['type'].str.lower()

df['type_clean'].value_counts()

type_clean
non-persian    1080
tabriz          964
heriz           811
kashan          787
hamadan         424
               ...
pole              1
collection        1
panel             1
renaissance       1
star              1
Name: count, Length: 281, dtype: int64